### ISSUE TITLE
Cannot open projects with VS 2015

### ISSUE THREAD

**Issue by ThomasBarnekow** [OfficeDev/Open-XML-SDK#187] opened 2017-03-19 14:43 UTC
Not sure whether everybody has already upgraded to VS 2017, given that it has only been released very recently. Anyhow, the recent commit entitled "Update projects to VS 2017" (dbaddb57) changed the .csproj files so that those projects can no longer be opened with VS 2015.

Using `DocumentFormat.OpenXml.csproj` as an example, here is the error message I get (with `[...]` meaning I omitted that part of the path):
```
[...]\Open-XML-SDK\DocumentFormat.OpenXml\DocumentFormat.OpenXml.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  [...]\Open-XML-SDK\DocumentFormat.OpenXml\DocumentFormat.OpenXml.csproj
```
I get the same error message for the other two projects contained in the solution.

Did you mean to only support VS 2017 going forward (which could be fine)? Otherwise, we need another solution referencing VS 2015 compatible .csproj files.

**Comment by robertmuehsig** [comment] 2017-03-19 18:14
I guess VS2017 is the way to go because the new .csproj base is vastly different and offers more possiblities (e.g. creating NuGet packages directly from it)

**Comment by ThomasBarnekow** [comment] 2017-03-19 19:31
For the avoidance of doubt, I'm not arguing against VS2017 being the way to go. I also planned to make the transition from VS2015 to VS2017 soon after its official release. And looking at just 2 open pull requests, I think we don't leave too many contributors behind. And if NuGet packages are now the preferred way of distributing releases rather than having people build their own, the "problem" might not be all that big.

BTW, I've just migrated my main project to the latest NuGet package, which worked just fine. So even if I waited a while before upgrading to VS2017, I would not have a problem. I was only planning to have a look at those unit tests (see the other issue I created), which I can't right now because I am still on VS2015.

**Comment by tarunchopra** [comment] 2017-03-21 07:06
@ThomasBarnekow : You are right; we broke something and project is not compiling with VS2015. It's supposed to work with VS 2015.

@tomjebo : Can you review what broke the VS 2015 compilation ?

**Comment by ThomasBarnekow** [comment] 2017-03-21 07:20
@tarunchopra, this is not a compile problem. As described in my original post, the project files cannot be opened with VS2015 because the project file format has been upgraded to VS2017. The VS2017 format is incompatible with the one used up to VS2015.

**Comment by tomjebo** [comment] 2017-03-21 16:02
@ThomasBarnekow thanks for bringing this up. I'll sync up with @twsouthwick and get this resolved.

**Comment by twsouthwick** [comment] 2017-03-21 16:15
This was by design as the tooling for VS2015 was preview and with VS2017 hitting RTM, that tooling is the way forward. The two project types don't work well together (having a project.json and the csproj in the same directory causes problems for the toolchains). I can't gather from the thread if this is a blocker (ie are people unable to upgrade to VS2017?).

@ThomasBarnekow  if you want to look at the project in VS2015, the code itself hasn't diverged at all, so feel free to checkout the commit before the merge and fix any tests there. Another option is to download the .NET CLI tools and use VS Code.

**Comment by ThomasBarnekow** [comment] 2017-03-21 18:02
@twsouthwick I personally don't have an issue with upgrading to VS2017 as I planned to do that anyhow. Other people might have a problem, though. 

I was just surprised that I could effectively not open the solution with VS2015, because the only project files I can see right now are `.csproj` files, e.g., `DocumentFormat.OpenXml.csproj`, which don't work with VS2015. I can't see `project.json` files anywhere, at least not in the vNext branch.

So, what exactly is the way forward? The current `.csproj` files that can't be opened with VS2015 but only VS2017? If so, we should be really clear in Readme.md that anybody wanting to compile the SDK or contribute to it must use VS2017 or whatever else is supported.

Leaving the legacy behind is totally fine in my eyes. People who just want to work with the SDK can now comfortably use NuGet packages. They no longer need to build the SDK themselves.

**Comment by twsouthwick** [comment] 2017-03-21 18:39
Yes, the README is being updated to address this issue. The way forward is to open in a tool that supports the new csproj format: VS2017, VS Code, VS for Mac, or .NET CLI

**Comment by ThomasBarnekow** [comment] 2017-03-21 19:16
Good. Once the README is updated, we can close this issue.

**Comment by ThomasBarnekow** [comment] 2017-03-30 08:47
@twsouthwick, you said the README is being updated but I can't see any update yet. Will this be done anytime soon?

I've also seen that the Change Log in the README does not reflect the latest **nine (9)** NuGet packages (see [here](https://dotnet.myget.org/feed/open-xml-sdk/package/nuget/DocumentFormat.OpenXml)). And if you look at the [gallery](https://dotnet.myget.org/gallery/open-xml-sdk) page for the Open XML SDK, the Change Log mentions Version 2.6.0, 2.6.1, and 3.0.0 (as "in progress"), but it does not mention **any** of the versions that you can actually download.

**Comment by twsouthwick** [comment] 2017-03-30 14:57
The [README](./README.md) in the repo has been updated but looks like you are looking at the feed description which has not. Only released versions are included in the README - ci builds (ie once with vNext in the name) are not included as those are not official releases. I'll update that readme.

**Comment by twsouthwick** [comment] 2017-03-30 15:04
I've updated the feed README to include the latest information

**Comment by ThomasBarnekow** [comment] 2017-03-30 20:09
@twsouthwick, I looked at both the README of this repository and at the feed.

Regarding the README (following the link you provided above), what exactly did you update? For example, it does not mention that VS2015 and earlier are no longer supported. It should mention what you already indicated above:

> The way forward is to open in a tool that supports the new csproj format: VS2017, VS Code, VS for Mac, or .NET CLI

The README also says the following:

> This project uses the **project.json** for the project build system. Please see the .NET Core SDK for more information on how to use this project type.

Is that still up-to-date?

The fact that you publish CI builds on myget.org is also a bit confusing (at least for me). And a CI build (2.7.2-vnext0027) is currently marked as the recommended **release** (rather than 2.7.1)?

**Comment by twsouthwick** [comment] 2017-03-31 00:30
> Regarding the README (following the link you provided above), what exactly did you update? For example, it does not mention that VS2015 and earlier are no longer supported. It should mention what you already indicated above:

We don't explicitly state it doesn't support VS2015, but we do say you need VS2017 or something compatible. I prefer to state what you need to open it, rather then list some of the things that won't work. What do you think? The current wording is in bullet 2: 

```
   Open the solution with an editor that supports the latest .NET project files, such as Visual Studio 2017, VS Code, VS for Mac, or .NET CLI. See https://www.microsoft.com/net/download/core for details.
```

> The README also says the following: ... This project uses the project.json 

Good catch. This is out of date and needs to be updated

> The fact that you publish CI builds on myget.org is also a bit confusing (at least for me). 

MyGet doesn't seem to differentiate between prerelease and non-prerelease and I'll look into why the latest build is marked as recommended. If you were to try to add these in VS, you'll only see the stable versions. If the name scheme is confusing, please see http://semver.org. This can be clarified in the README as well if you think that would help.

**Comment by ThomasBarnekow** [comment] 2017-04-01 13:14
> We don't explicitly state it doesn't support VS2015, but we do say you need VS2017 or something compatible. I prefer to state what you need to open it, rather then list some of the things that won't work. What do you think?

I would also say that VS2015 and earlier are not supported. Otherwise, people would have to find out that VS2015, for example, does not support the latest .NET project files. Thus, you could add something like the following:
```
For clarity, Visual Studio 2015 and earlier do not support the latest .NET project files and cannot be used to open the solution.
```

Regarding the *stable* versions on myget.org, you are right in case people use the VS GUI. However, people might use the Package Manager console to install the package as described by the example provided in the README:
```
PM> Install-Package DocumentFormat.OpenXml -Version <version retrieved from the web>
```
When determining the *version retrieved from the web* by following the [link](https://dotnet.myget.org/feed/open-xml-sdk/package/nuget/DocumentFormat.OpenXml) that is provided in the README, people see **2.7.2-vnext0027** (status April 1) as the **recommended release**.

So, yes, I would think that explaining the version naming scheme in the README would definitely help in this case (because myget.org incorrectly flags a prerelease as the recommended release).

**Closed** 2017-04-10 17:00 UTC

**Comment by vibs2006** [comment] 2018-04-13 17:19
To run the project in Visual Studio 2015 please revert to a commit in which Visual Studio 2015 was used. 

If you are not sure then run the following command on git command line. 

Navigate to git master branch
```
git checkout master
```
1. Please ensure that you backup current directory to another location before executing the following step. 
2. You have closed your visual studio completely so that there are no file access errors. 

You can see history of commits by the following line 
```
git log --oneline --graph --decorate
```
![image](https://user-images.githubusercontent.com/18658498/38748718-a45c1252-3f6c-11e8-8c92-e541e220ced3.png)

In this case are reverting to commit id **_3f36da8_**
```
git reset --hard 3f36da8 && git clean -f -d
```
Now try opening the solution in Visual Studio 2015 and it should work!

**Comment by vibs2006** [comment] 2018-04-14 03:37
@twsouthwick My git reset fix was just to run a sample project on VS2015 for users who just want to look at this project how it works. I never meant it for take it to production or use it generally. For all practical purpose even Visual Studio 2017 has a community but there are users who don't have user rights to install new software on their system. So this fix might be helpful for them to get a 'quick glimpse' of main methods that are being used in this project.

**Comment by twsouthwick** [comment] 2018-04-14 05:04
Would something like https://github.com/KirillOsenkov/SourceBrowser be helpful for this (such as at http://source.dot.net)? I've been thinking of setting that up for this project for easy browsing and searching via symbols
