### ISSUE TITLE
Where are the w:headers and w:header elements?

### ISSUE THREAD

**Issue by arlm** [OfficeDev/Open-XML-SDK#98] opened 2016-06-27 10:26 UTC
I understand that WordprocessingML got w:headers and w:header elements added on the standards, so that w:tcPr can have a w:headers child and the latest could have any amount of w:header elements as children.

I could not find any reference or matching element whatsoever to use it. How could one get a reference to these elements by class name?

> Annex M. (informative) Differences Between ECMA-376:2012 and ECMA-376:2006 
> 
> This annex is informative.
> 
> This annex highlights the differences between the versions of the Strict form of the Office Open XML schemas, as defined in ECMA-376:2012 and the schemas as defined by ECMA-376:2006.
> 
> ...
> - The header element (§17.4.18) was added
> - The headers element (§17.4.19) was added

And

> 17.4.18 header (Header Cell Reference)
> 
> This element specifies a reference, using a unique identifier, to a table header cell that is associated with the current table cell. The identifier representing the reference shall be stored on this element’s val attribute and is used to reference the unique identifier value of the id attribute of a header cell tc element of the current table.
> The contents of the table header cell tc element designated by the specific unique identifier in its id attribute shall be used as the table header information associated with the table cell that references that specific unique identifier.
> If this element is omitted or the value of the header cell identifier cannot be resolved, no header cell shall be associated with the current table cell.
> 
> ...
> 
> 17.4.19 headers (Header Cells Associated With Table Cell)
> 
> This element specifies the list of header cells, as specified by children header elements, that provide header information associated with the current table cell. Each header cell shall specify a unique identifier, as specified by the use of the attribute id on the header cell tc element. This element is typically used to gather header information about data and sub header cells.
> If this element is omitted or no children header element exists, no header cell shall be associated with the given table cell.
> 
> ```
> <w:tbl>
>   …
>   <w:tr>
>     …
>     <w:tc >
>       …
>     </w:tc>
>     <w:tc w:id="HeaderA">
>        …
>       <w:p>
>         <w:r>
>           <w:t>A</w:t>
>         </w:r>
>       </w:p>
>     </w:tc>
>     …
>   </w:tr>
>   <w:tr>
>     …
>     <w:tc w:id="HeaderC">
>       …
>       <w:p>
>         <w:r>
>           <w:t>C</w:t>
>         </w:r>
>       </w:p>
>     </w:tc>
>     <w:tc>
>       <w:tcPr>
>         …
>         <w:headers>
>           <w:header w:val="HeaderA" />
>           <w:header w:val="HeaderC" />
>         </w:headers>
>         …
>       </w:tcPr>
>       <w:p>
>         <w:r>
>           <w:t>x1</w:t>
>         </w:r>
>       </w:p>
>     </w:tc>
>     …
>   </w:tr>
> </w:tbl>
> ```

**Comment by Josh-Curry** [comment] 2016-10-28 21:26
Hi arlm, after reviewing the ISO/IEC 29500 standard and the Open XML SDK project, it is our determination that this is something that is currently missing and should be added. The request has been logged and will be reviewed for possible addition to the SDK in a future release of the project. Please let me know if you would like to provide any further details. Otherwise, we will consider this issue closed for now. Thank you.

**Comment by twsouthwick** [comment] 2018-05-02 17:15
I'm reopening this so we can track it in the SDK

**Comment by twsouthwick** [comment] 2020-03-24 00:29
I believe this is a duplicate of #492 - please reopen with more details if that is not the case.

**Closed by twsouthwick** 2020-03-24 00:29 UTC
Labels: schema
