### ISSUE TITLE
Merge cells in a Docx file.

### ISSUE THREAD

**Issue by VenkataSri** [OfficeDev/Open-XML-SDK#283] opened 2017-11-02 08:57 UTC
Hi, I have a problem with OpenXML version 2.5.  I have created a table using rowspan and colspan.  but while converting in Docx the display is getting changed.  I am enclosing the HTML and screenshot of the output.  If someone has any solution that would be a great help.

Thank you,
Venkata
<img width="414" alt="table_format" src="https://user-images.githubusercontent.com/33311194/32317475-e897fc32-bfd9-11e7-8179-2e0e926ddf93.png">

**Comment by twsouthwick** [comment] 2017-11-02 19:58
Can you provide a repro?

**Comment by VenkataSri** [comment] 2017-11-03 11:21
Sorry I didnt get what you are talking about..

Thanks
Srikantha

**Comment by twsouthwick** [comment] 2017-11-03 15:51
A repro (preferably a minimum viable repro) is code that can be taken and run to see the issue. People often do it inline (see markdown support for [code](https://guides.github.com/features/mastering-markdown/)) or provide a gist or a whole repo if it is more complicated.

Simply put, can you include the code you are using so we can reproduce it (in other words, a repro)?

**Comment by VenkataSri** [comment] 2017-11-06 09:36
Hi, I cant send the code, but here are the steps to reproduce the same.
1. Reading the HTML content from Web page.
2.  Taking the Docx template from physical folder.
3.  Embedding the HTML content in the docx file
4. Finally generating a PDF from the embedded docx.

When document is generated in that rowspan is not merging the cells as per the attached screenshots.

Please help.

Thanks

**Comment by ThomasBarnekow** [comment] 2017-11-06 19:11
It is impossible to see whether you made mistakes without seeing your code. However, the solution is easy. The Open XML SDK basically helps you produce Open XML markup. Thus, you need to make sure you understand what Open XML markup (not HTML or anything else) EXACTLY you need to create the desired effect in Microsoft Word or other compatible word processors.

One way of ensuring you produce the right markup is to (1) create a Word document with the desired content and look and feel and then (2) produce a PDF from that Word document that looks like what you‘d expect.

**Comment by twsouthwick** [comment] 2017-11-12 00:08
@VenkataSri  I'm going to close this as no repro unless you can provide steps (ie code) for us to reproduce this.

**Closed** 2017-11-17 18:30 UTC
Labels: bug, needs-repro
