### ISSUE TITLE
Official NuGet Package

### ISSUE THREAD

**Issue by martinfletcher** [OfficeDev/Open-XML-SDK#144] opened 2017-01-12 14:19 UTC
Hello,

Is there an official NuGet package for this SDK? My company only allows use of packages from trusted sources (nuget.org), but can only find unofficial packages.

Please can someone point me in the right direction, and provide one if not already available?

Thanks,

Martin

**Comment by robertmuehsig** [comment] 2017-01-12 14:23
=> https://github.com/OfficeDev/Open-XML-SDK/issues/2#issuecomment-271601375

**Comment by martinfletcher** [comment] 2017-01-12 14:44
Thanks @robertmuehsig, but is there a package on NuGey.org?

**Comment by robertmuehsig** [comment] 2017-01-12 15:12
Currently not - I'm waiting as well (and for the .NET Core support) ;)

**Comment by mredman** [comment] 2017-01-12 18:59
There seem to be no libraries that can generate word documents that support .net core 1.1, including commercial ones.

**Comment by twsouthwick** [comment] 2017-01-12 20:31
There is a pre-release of the latest build (which supports .NET 4.5 and .NET Standard 1.3) on myget at https://dotnet.myget.org/F/open-xml-sdk/api/v3/index.json. See the [README](https://github.com/OfficeDev/Open-XML-SDK#ci-builds) for more details.

> My company only allows use of packages from trusted sources (nuget.org), but can only find unofficial packages.

Do you mean by this that a custom feed is not trusted, but nuget.org is? If so, please be aware that nuget.org allows anyone and everyone to push a package there. For enterprises, the recommendation is to set up a private feed (such as via MyGet or VSTS Package Management) and add packages that you have vetted there. The custom feed this is locked down and this project is the only one that feeds into it.

**Comment by mredman** [comment] 2017-01-13 07:51
@twsouthwick Thanks, this works.

**Comment by tomjebo** [comment] 2017-01-13 16:54
Closing.

**Closed by tomjebo** 2017-01-13 16:54 UTC

**Comment by sandrock** [comment] 2017-01-19 17:39
Hello. Maybe I'm stupid and the 2 other guys in my team too: I can't find a way to install the package.

```
PM> install-package https://dotnet.myget.org/F/open-xml-sdk/api/v3/index.json
install-package : Unable to find package 'https://dotnet.myget.org/F/open-xml-sdk/api/v3/index.json'.
 
PM> install-package https://dotnet.myget.org/F/open-xml-sdk/api/v2
install-package : Unable to find package 'https://dotnet.myget.org/F/open-xml-sdk/api/v2'.
 
PM> install-package open-xml-sdk -Source https://dotnet.myget.org/F/open-xml-sdk/api/v2
install-package : Unable to find package 'open-xml-sdk'.
 
PM> install-package open-xml-sdk -Source https://dotnet.myget.org/F/open-xml-sdk/api/v3/index.json
install-package : An error occurred while loading packages from 'https://dotnet.myget.org/F/open-xml-sdk/api/v3/index.json': The remote server returned an error: (404) Not Found.
 
PM> 
```

**Can you write just a little bit of documentation? Or maybe a link to the generic documentation on how to install a package from this kind of repository? That would be great.**

Yes, we searched online and found nothing that works. 

* https://dotnet.myget.org/gallery contains nothing *visible*
* ["install package" search on myget](http://docs.myget.org/search?q=install%20package) contains nothing 
* tried [that too](http://stackoverflow.com/a/35439417/282105) with no success (Unable to find package 'open-xml-sdk')

**Comment by twsouthwick** [comment] 2017-01-19 17:47
Hi @sandrock. This issue you're hitting is conflating the term *package* and *package feed*. The *package* you want is `DocumentFormat.OpenXml`, while the *package feed* (or *package source* - the term is used interchangeably) is the url you tried. You still install the same way (ie `Install-Package DocumentFormat.OpenXml`), but you need to add the feed to the source of feeds via a configuration option. See https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior for details on configuring this. Usually, a `NuGet.config` file is placed in the directory and the config options added there so that the sources are persisted in version control.

I've created an issue #149 to track adding this to the readme.

**Comment by twsouthwick** [comment] 2017-01-19 17:49
@sandrock I only looked at the first couple of tries you did. Try 

```
PM> install-package DocumentFormat.OpenXml -Source https://dotnet.myget.org/F/open-xml-sdk/api/v3/index.json
 ```

**Comment by twsouthwick** [comment] 2017-01-19 17:51
Here's a link to the gallery as well: https://dotnet.myget.org/gallery/open-xml-sdk. I'm seeing the package - let me know if you're not

**Comment by sandrock** [comment] 2017-01-19 19:03
Thank you for your help @twsouthwick 

It seems I got the package name wrong (DocumentFormat.OpenXml). There was no place in the readme file with this name. I wonder how anyone could have guessed it?

About the command you suggested: I already tried this one. The result is "An error occurred while loading packages from '...json': The remote server returned an error: (404) Not Found.".

I did the nuget.config file thing with no success.   
The `install-package DocumentFormat.OpenXml` installs a fake package from nuget.org.   
The `install-package DocumentFormat.OpenXml -Version 2.7.0-vnext0061` says there are no package with this version.  
By the way, there is a funny line in the nuget documentation that says "Although you can modify the file in any text editor, NuGet (v3.4.3 and later) *silently ignores the entire configuration file if it contains malformed XML* (mismatched tags, invalid quotation marks, etc.)." (Why so much hate for the users?)

Strange thing: `nuget.exe install DocumentFormat.OpenXml -Version 2.7.0-vnext0061` *is able* to download the package (but it does not "install" the package).  The verbose says that the package is being downloaded from `GET https://dotnet.myget.org/F/open-xml-sdk/api/v2/package/DocumentFormat.OpenXml/2.7.0-vnext0061`. I think this means my config file is OK.

From this point I suppose the `Install-Package` command fails to consider the package source (by config or by argument). Now I know the issue is not yours to fix but I would love to get an insight if you have one. Tomorrow I will try with my colleagues on other PCs.

NuGet Version: 3.4.4.1321

**Comment by twsouthwick** [comment] 2017-01-19 19:16
> I wonder how anyone could have guessed it?

Good call on needing to call out the library name. I think we had the assumption people would add it via the UI where the package shows up. Also, by default, packages tend to be the name of the project. However, this is not a hard and fast rule and not something we should assume is obvious.

> I did the nuget.config file thing with no success.

As far as `install-package` not working, did you try to restart VS? I've found that the package sources tend to get cached and not pick up changes you've made to any `NuGet.config` files (I've logged a bug here that may be related: https://github.com/NuGet/Home/issues/4285). The `nuget.exe` command reloads the sources each time (as it's a new process each time).

> Why so much hate for the users?

I'm not aware about the ignoring the config file issue - I'd recommend opening a bug in the NuGet repo so there can be some discussion. There appears to be a [few issues](https://github.com/NuGet/Home/issues?q=is%3Aissue+silently+ignore+is%3Aclosed).

**Comment by sandrock** [comment] 2017-01-24 14:10
Thank you again  @twsouthwick 

Restarting VS worked in a way.

`PM> Install-Package DocumentFormat.OpenXml -Version 2.7.0-vnext0061` still does not work but...

`PM> Install-Package DocumentFormat.OpenXml -Version 2.7.0-vnext0061 -Source https://dotnet.myget.org/F/open-xml-sdk/api/v2` works!

I will try all that on other PCs to better diagnose the issue. Then I will contribute to the nuget side if necessary.
