### ISSUE TITLE
Documents fail to open on Mono with System.IO.Packaging library

### ISSUE THREAD

**Issue by owlwang** [OfficeDev/Open-XML-SDK#221] opened 2017-07-24 10:48 UTC
When I use the following code：
[https://msdn.microsoft.com/en-us/library/office/gg575571.aspx](https://msdn.microsoft.com/en-us/library/office/gg575571.aspx)
```
static void ReadExcelFileDOM(string fileName)
{
    using (SpreadsheetDocument spreadsheetDocument = SpreadsheetDocument.Open(fileName, false))
    {
        WorkbookPart workbookPart = spreadsheetDocument.WorkbookPart;
        WorksheetPart worksheetPart = workbookPart.WorksheetParts.First();
        SheetData sheetData = worksheetPart.Worksheet.Elements<SheetData>().First();
        string text;
        foreach (Row r in sheetData.Elements<Row>())
        {
            foreach (Cell c in r.Elements<Cell>())
            {
                text = c.CellValue.Text;
                Console.Write(text + " ");
            }
        }
        Console.WriteLine();
        Console.ReadKey();
    }
}
```

 SpreadsheetDocument.Open() will report error
**PackageRelationship target must be relative URI if TargetMode is Internal.
Parameter name: targetUri**
![ece33856-977e-4ca2-a4ed-130577397063](https://user-images.githubusercontent.com/13383393/28519921-0782dae2-70a0-11e7-8870-af5043796c80.png)

IDE: Visual Studio for Mac
.NET Runtime: Mono 5.0.1.1
OpenXML: 2.7.2.0
OS: macOS 10.12.5

**Comment by tarunchopra** [comment] 2017-07-24 16:07
Hello @owlwang : 

Please share your .xlsx file so that we can have a look. Looks like there is an issue with the relationships in the *.xml.rels file. Kindly ensure that the target is set to relative link when TargetMode is set to internal.

Thx

**Comment by owlwang** [comment] 2017-07-25 02:27
Here is the .xlsx file
[task.xlsx](https://github.com/OfficeDev/Open-XML-SDK/files/1171746/task.xlsx)

It is created by the following code:

[https://msdn.microsoft.com/en-us/library/office/ff478153.aspx?cs-save-lang=1&cs-lang=csharp#code-snippet-2](https://msdn.microsoft.com/en-us/library/office/ff478153.aspx?cs-save-lang=1&cs-lang=csharp#code-snippet-2)

```
public static void CreateSpreadsheetWorkbook(string filepath)
{
    // Create a spreadsheet document by supplying the filepath.
    // By default, AutoSave = true, Editable = true, and Type = xlsx.
    SpreadsheetDocument spreadsheetDocument = SpreadsheetDocument.
        Create(filepath, SpreadsheetDocumentType.Workbook);

    // Add a WorkbookPart to the document.
    WorkbookPart workbookpart = spreadsheetDocument.AddWorkbookPart();
    workbookpart.Workbook = new Workbook();

    // Add a WorksheetPart to the WorkbookPart.
    WorksheetPart worksheetPart = workbookpart.AddNewPart<WorksheetPart>();
    worksheetPart.Worksheet = new Worksheet(new SheetData());

    // Add Sheets to the Workbook.
    Sheets sheets = spreadsheetDocument.WorkbookPart.Workbook.
        AppendChild<Sheets>(new Sheets());

    // Append a new worksheet and associate it with the workbook.
    Sheet sheet = new Sheet() { Id = spreadsheetDocument.WorkbookPart.
        GetIdOfPart(worksheetPart), SheetId = 1, Name = "mySheet" };
    sheets.Append(sheet);

    workbookpart.Workbook.Save();

    // Close the document.
    spreadsheetDocument.Close();
}
```
And I found the content of the workbook.xml.rels is:

```
<?xml version="1.0" encoding="utf-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="/xl/worksheets/sheet1.xml" Id="R7cd05896eed0457d" />
<Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="/xl/sharedStrings.xml" Id="R4113d0c1ffe741c9" />
<Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="/xl/worksheets/sheet2.xml" Id="Raaa43d3985de47bf" />
</Relationships>
```
You mean these target paths should be "xl/worksheets/sheet1.xml"  instead of "/xl/worksheets/sheet1.xml" ?

**Comment by tarunchopra** [comment] 2017-07-28 05:42
@owlwang : I'll look into the file and get back.

**Comment by tarunchopra** [comment] 2017-07-28 20:57
@owlwang : 

Yes, you are right on this one --  _'You mean these target paths should be "xl/worksheets/sheet1.xml"  instead of "/xl/worksheets/sheet1.xml_" ?'.

As a test; I opened your .xlsx file in ODE tool and added '/' in front of 'worksheets/sheet1.xml' in workbook.xml.rels. Excel application complained about the file as it does not like that extra '/'. 

This proved that the format of Target should not start with '/'.

Does this resolve your issue ?

**Comment by owlwang** [comment] 2017-07-29 01:28
@tarunchopra 

Thank you for your reply.

But I mean I used the official code [MSDN](https://msdn.microsoft.com/en-us/library/office/ff478153.aspx#Anchor_3) to create an error file.

IDE: Visual Studio for Mac
.NET Runtime: Mono 5.0.1.1
OpenXML: 2.7.2.0
OS: macOS 10.12.5

Is there a problem with the official code? And what should I do to generate the correct Excel file？

**Comment by tarunchopra** [comment] 2017-07-31 19:34
@owlwang : Ok; I tried opening your file in VS on Windows machine and it does not throw any such error. I believe you are testing this on MAC so I need to get it verified on MAC. Give me day or so to test and get back.

**Comment by tarunchopra** [comment] 2017-08-08 07:27
@owlwang : 

Sorry for the delay, i tried reproducing the issue on MAC and was facing following 'Absolute URIs are not supported' issue - https://stackoverflow.com/questions/43783640/c-sharp-openxml-error-with-word-online-files-absolute-uris-are-not-supported. After adding following line ; Environment.SetEnvironmentVariable("MONO_URI_DOTNETRELATIVEORABSOLUTE", "true"); I was able to get rid of the 'Absolute URIs' issue and open file w/o any problem. I didn't face the issue you are facing i.e. TargetMode is internal. 

Can you please try following code and see if it resolves your issue? Also, before executing the code, open task.xlsx file in Excel and ensure that it's has valid content and excel app is able to open it.

using System;
using System.IO.Packaging;
using System.Windows;
using DocumentFormat.OpenXml.Packaging;
using System.IO;
using System.Reflection;

namespace TestOpenXML
{
    class MainClass
    {

        public static void Main(string[] args)
        {
            Environment.SetEnvironmentVariable("MONO_URI_DOTNETRELATIVEORABSOLUTE", "true");
            using (SpreadsheetDocument spreadsheetDocument = 
            SpreadsheetDocument.Open("/TestOpenXML/task.xlsx", true))
            {
                Console.Write(spreadsheetDocument.WorkbookPart.Workbook.AbsolutePath);
            }
        }
    }
}


Thx

**Comment by owlwang** [comment] 2017-08-10 07:01
@tarunchopra 
I'm sorry to reply you so late.

I've tested the code you gave, and it no longer throws exception. 
Add the code `Environment.SetEnvironmentVariable("MONO_URI_DOTNETRELATIVEORABSOLUTE", "true");` can fix this bug.

Thank you for your help.

**Comment by tarunchopra** [comment] 2017-08-10 07:02
Awesome, closing the thread

**Comment by Depechie** [comment] 2017-10-13 12:29
@tarunchopra I'm testing this with .Net standard lib on Xamarin Forms and getting same error when I try to reopen a saved spreadsheet.
Adding the `Environment.SetEnvironmentVariable("MONO_URI_DOTNETRELATIVEORABSOLUTE", "true");` has no effect.

Is there anything else I need to fix?

**Comment by Depechie** [comment] 2017-10-13 12:32
Ha seems I'm in same boot as issue #249

**Comment by Depechie** [comment] 2017-10-13 12:40
Ha when I add the Environment.SetEnvironmentVariable("MONO_URI_DOTNETRELATIVEORABSOLUTE", "true"); line in the method where I create the excel AND in the method where I read out the created excel, everything works as expected.

**Comment by twsouthwick** [comment] 2017-11-17 03:54
I'm reopening this as the fix put in only fixes creating documents, not opening them.

**Comment by igitur** [comment] 2017-11-20 16:29
Did https://github.com/mono/mono/pull/3630 not fix this?

**Comment by twsouthwick** [comment] 2017-11-20 16:38
It did, when running against the System.IO.Packaging within Mono; now with .NET Standard, the System.IO.Packaging is pulled in from CoreFx when running on Xamarin platforms. The CoreFx version does have this fix yet.

**Comment by twsouthwick** [comment] 2017-12-07 20:19
FYI: The fix I submitted to CoreFX has been merged in and will be available with the next release of `System.IO.Packaging`. I'll update the build to use a CI build of CoreFX so we'll have the fix.

**Comment by twsouthwick** [comment] 2017-12-12 03:51
@Depechie The fix has been merged into System.IO.Packaging and available in a CI build. If you can give it a try to ensure the fix works, that would be awesome. Please try the package here: https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.IO.Packaging/4.5.0-preview1-26011-03. Once it is released, we'll update the project to take a dependency on it. If you explicitly reference this package along with 2.7.2 of the SDK, you should not need any environment hackery.

**Comment by twsouthwick** [comment] 2018-04-06 19:07
@Depechie This is also available on NuGet via prerelease: https://www.nuget.org/packages/System.IO.Packaging/4.5.0-preview1-26216-02

**Comment by Depechie** [comment] 2018-04-08 10:01
Adding the latest preview nuget package of System.IO.Packaging, does indeed solve the problem!
Nice :)

**Comment by twsouthwick** [comment] 2018-04-09 17:53
Thanks for the update! Once there is a stable release of it, we'll update the SDK to depend on it

**Closed** 2018-05-31 17:28 UTC
Labels: blocked: corefx System.IO.Packaging, bug
