### ISSUE TITLE
WordprocessingDocument XML not updating after MainDocumentPart.Document is accessed

### ISSUE THREAD

**Issue by ylw633** [OfficeDev/Open-XML-SDK#222] opened 2017-07-25 20:26 UTC
I am trying to follow the instructions of this MSDN article: https://blogs.msdn.microsoft.com/ericwhite/2008/12/10/working-with-in-memory-open-xml-documents/

My example is only slightly modified from it. I extracted the code to update text into its own function:
 ```c#
	public static void TestUpdateText(WordprocessingDocument doc, Func<string, string> contentFunc)
	{
		XDocument xdoc = doc.MainDocumentPart.GetXDocument();
		XNamespace w = "http://schemas.openxmlformats.org/wordprocessingml/2006/main";
		XElement firstParagraph = xdoc
		  .Element(w + "document")
		  .Element(w + "body")
		  .Element(w + "p");
		if (firstParagraph != null)
		{
			string text = firstParagraph
			  .Descendants()
			  .Where(n => n.Name == w + "t" || n.Name == w + "ins")
			  .Select(n => (string)n)
			  .StringConcatenate();
			firstParagraph.ReplaceWith(
			  new XElement(w + "p",
				new XElement(w + "r",
				  new XElement(w + "t", contentFunc(text)))));
			// write the XDocument back into the Open XML document
			doc.MainDocumentPart.PutXDocument();
		}
	}
```

therefore the main function is updated to:
```c#
    static void Main(string[] args)
	{
		byte[] byteArray = File.ReadAllBytes(@"dummy-testing.docx");
		using (MemoryStream mem = new MemoryStream())
		{
			mem.Write(byteArray, 0, (int)byteArray.Length);
			using (WordprocessingDocument wordDoc = WordprocessingDocument.Open(mem, true))
			{
				TestUpdateText(wordDoc, t => t.ToUpper() + " First Change");
				var tempDoc = wordDoc.MainDocumentPart.Document;
				TestUpdateText(wordDoc, t => t.ToLower() + " Second Change");
			}

			using (FileStream fileStream = new FileStream(@"dummy-copy.docx", System.IO.FileMode.Create))
			{
				mem.WriteTo(fileStream);
			}
		}
	}
```

The issue is quite strange, if I comment out the line
```c#
var tempDoc = wordDoc.MainDocumentPart.Document;
```

the final document will contain both "First Change" and "Second Change", but if I don't comment it out the final document will only contain "First Change" only. It seems whenever .Document property is accessed the part can no longer be updated via XML directly. Is this a bug or a restriction that has been documented somewhere else?

By the way, updating MainDocumentPart with API still works, for example, if I add the following line
```c#
tempDoc.AppendChild<Paragraph>(new Paragraph()).AppendChild<Run>(new Run()).AppendChild<Text>(new Text() { Text = "HELLO!!!" });
```
the final document will have the HELLO text.

**Comment by ylw633** [comment] 2017-07-25 20:31
"dumm-testing.docx" is just an arbitrary near blank Word document I created using Word 2017, only contain the text "this is a test document".

**Comment by ThomasBarnekow** [comment] 2017-07-26 08:09
@ylw633, please have a look at issue #198, in which I describe the incompatibility between the Open XML SDK and the PowerTools for Open XML. I provided a way to fix that general issue in a [pull request](https://github.com/OfficeDev/Open-Xml-PowerTools/pull/139) for the Open XML PowerTools that got merged a while ago.

That pull request also contains unit tests which demonstrate the issue you are facing and the solution, which is to use the (1) `PowerToolsBlock` or (2) `StronglyTypedBlock` classes to demarcate usages of (1) the Open XML PowerTools or (2) the strongly typed classes provided by the Open XML SDK where both are used together.

Looking at your code, I assume that you just wanted to demonstrate that usages of the strongly typed classes in such scenario can cause issues. The line of code causing the issue is not used in your sample code and should otherwise not be there. Right?

**Comment by ylw633** [comment] 2017-07-26 15:43
Thank you @ThomasBarnekow the information is really helpful!
Though the reason is different but it ends with same result. In fact, we had an existing component that first construct a document using strongly typed mechanism (SDK api), then merge the result with several documents using XML overwrite (PowerTools way). Since the changes of direct overwrite were not taken as mentioned previously, our code forced it by performing:
```c#
part.RootElement.InnerXml = documentContent;
```
However occasionally we get this exception
```c#
Index was outside the bounds of the array
   at DocumentFormat.OpenXml.TagAttributeTranslator.get_Trait()
   at DocumentFormat.OpenXml.OpenXmlElement.TrySetFixedAttribute(String namespaceUri, String localName, String value, Boolean strictTranslation)
   at DocumentFormat.OpenXml.OpenXmlElement.LoadAttributes(XmlReader xmlReader)
   at DocumentFormat.OpenXml.OpenXmlLeafElement.Populate(XmlReader xmlReader, OpenXmlLoadMode loadMode)
   at DocumentFormat.OpenXml.OpenXmlElement.Load(XmlReader xmlReader, OpenXmlLoadMode loadMode)
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.Populate(XmlReader xmlReader, OpenXmlLoadMode loadMode)
   at DocumentFormat.OpenXml.OpenXmlElement.Load(XmlReader xmlReader, OpenXmlLoadMode loadMode)
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.Populate(XmlReader xmlReader, OpenXmlLoadMode loadMode)
   at DocumentFormat.OpenXml.OpenXmlElement.Load(XmlReader xmlReader, OpenXmlLoadMode loadMode)
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.Populate(XmlReader xmlReader, OpenXmlLoadMode loadMode)
   at DocumentFormat.OpenXml.OpenXmlElement.Load(XmlReader xmlReader, OpenXmlLoadMode loadMode)
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.Populate(XmlReader xmlReader, OpenXmlLoadMode loadMode)
   at DocumentFormat.OpenXml.OpenXmlElement.ParseXml()
   at DocumentFormat.OpenXml.OpenXmlElement.MakeSureParsed()
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.get_FirstChild()
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.set_InnerXml(String value)
```

I tried to resolve this by not doing that but still need to make merging work, so I am weighing a better solution. Your answer does provide me with a direction to go, thank you very much for your help!

**Comment by ThomasBarnekow** [comment] 2017-07-26 16:21
You are welcome, @ylw633. And for everybody else, the short form of the solution is to structure your code roughly as follows:
```
// Your strongly typed code here

using (new PowerToolsBlock(wordDoc))
{
    // Your PowerTools/Linq-to-XML code here
}

// Your strongly typed code here
```
And if you mainly use the PowerTools approach and only occasionally the strongly typed classes, you would turn it around as follows:
```
// Your PowerTools/Linq-to-XML code here

using (new StronglyTypedBlock(wordDoc))
{
    // Your strongly typed code here
}

// Your PowerTools/Linq-to-XML code here
```

**Closed** 2017-07-27 20:50 UTC

**Comment by kentrob** [comment] 2017-11-02 12:01
This pull request saved my life! Many thanks to you and Eric for all the great work you do on the OpenXML Power Tools library.
