### ISSUE TITLE
Markup Compatibility Extensibility (MCE) doesn't work properly in 2.5

### ISSUE THREAD

**Issue by EricWhiteDev** [OfficeDev/Open-XML-SDK#30] opened 2015-01-27 11:54 UTC
If you set FileFormatVersion.Office2010, then it correctly picks the 'Choice' element of an AlternateContent block for an inline text box.  If you set FileFormatVersion.Office2013, then it incorrectly picks the Fallback element of an AC block.

```
openSettings = new OpenSettings();
openSettings.MarkupCompatibilityProcessSettings =
    new MarkupCompatibilityProcessSettings(
        MarkupCompatibilityProcessMode.ProcessAllParts,
        FileFormatVersions.Office2010);
using (var wDoc = WordprocessingDocument.Open(outFile.FullName, true, openSettings))
```

We should investigate other AlternateContent blocks, and see if this same behavior is there.  I suspect that it is.  I believe that the fix is where we change the code to take the Choice block if the setting version is equal to **or greater** than the implementation version for the Choice block.  Right now it appears that it takes the choice only if the version specified for MarkupCompatibilityProcessSettings is **equal** to the implementation version for the Choice block.

We should consider carefully how to fix this – we should have at least a point release (v2.6) to fix these types of bugs, because they could possibly cause different behavior in existing programs.

**Comment by twsouthwick** [comment] 2017-11-17 03:30
@EricWhiteDev Did you ever root cause this?

**Comment by twsouthwick** [comment] 2020-03-24 00:07
Closing as no-repro

**Closed by twsouthwick** 2020-03-24 00:07 UTC
Labels: bug, needs-repro
