### ISSUE TITLE
openxml doesn't retrieve the same value than what VBA gives

### ISSUE THREAD

**Issue by jmclej** [OfficeDev/Open-XML-SDK#76] opened 2016-02-19 15:20 UTC
Hello,
I am using open xml sdk 2.5 with Visual Studio C# and I have noticed a bug and I am asking you if you could correct it please?
I have the cell D5 in an Excel spreadsheet that contains the formula "=3000000/D10" and D10 cell contains the formula "=1.41973/1.2939".

When I read this cell within VBA macro like this : Worksheets("My sheet").Cells(5, 4), I get 2734111.41555084 but when I read it via openxml, the cell contains here 2734111.41555084**47** (see the extra 47), which is wrong.

I expect to get the same result as VBA gives.

As microsoft states here ( https://support.office.com/en-us/article/Excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3 ), we understand that Excel never gives more than 15 digits, so neither should openxml. With more than 15 '#', it should only add non-significative zeros. But in my case openxml gives 17 digits (2734111.4155508447) instead of the 15 that I am talking about (2734111.41555084).

Unfortunately, it is not just about truncating the last 2 digits as the calculations are done in binary and then converted back to decimal system. You can see that when you type in a calculator 3000000/(1.41973/1.2939), the result is 2734111.415550844**17**4596578222619, the digits 16 and 17 are here "17", compares to "47" that Excel gives (2734111.41555084**47**).

You can find additional info in link given in the answer there ( http://stackoverflow.com/questions/35368637/openxml-and-excel-15-digits-number-limit?answertab=votes#tab-top ).

Can this be corrected please in Open XML ? Or is there a workaround (I doubt as I don't have the source code of Excel, I wouldn't have the knowledge to know how to handle the floating-point handling) ?
I am reproducing this bug with your actual version 2.6 which I've just recompiled.

Regards,

**Comment by EricWhiteDev** [comment] 2016-02-19 16:18
Hi,

The Open-Xml-Sdk gives *exactly* the values that you find in the excel file, which are definitely different from what you see in VBA.

The issue is pretty complicated - the values that you see in VBA have been formatted per the styles part, and it is non-trivial code to apply that information.

I recently put together a module that goes a long way towards getting the values that you want.  Please take a look at the following screen-cast:

http://openxmldeveloper.org/blog/b/openxmldeveloper/archive/2015/12/14/smldataretriever-better-approach-for-retrieving-spreadsheet-data.aspx

I am not certain that this will give you exactly what you want - please try it out, let me know.

Cheers,

**Comment by tarunchopra** [comment] 2017-01-23 21:05
Closing the issue as it’s supposed to be resolved by the module that Eric suggested. Please open\reactivate a thread if you still need help

**Closed by tarunchopra** 2017-01-23 21:05 UTC
