### ISSUE TITLE
Adding parts to WorksheetPart derived class throws exception

### ISSUE THREAD

**Issue by rmboggs** [OfficeDev/Open-XML-SDK#720] opened 2020-05-18 20:45 UTC
**Description**
When I try to add parts to a worksheet part within a class derived from WorksheetPart, such as SpreadsheetPrinterSettingsPart or VmlDrawingPart, an OpenXmlPackageException is thrown with a message "The part cannot be added here."  This just started when I updated the reference SDK to 10.0 or 10.1.  The code works as expected when built and run against SDK version 9.1 or earlier.

I'm still trying different things to understand this issue better but this is what I am observing in my code.  However, if I open and existing workbook and simply add the part to a worksheet, it works fine.  The main difference that I can tell is that the error happens in my code that inherits from WorksheetPart.  Please let me know if there are any additional questions.

**Information**
- netstandard2.0
- DocumentFormat.OpenXml Version: 10.0+

**Repro**

```csharp
// Please add a self-contained, minimum viable repro of the issue.
// If you require external resources, please provide a gist or GitHub repro
// An Xunit style test is preferred, but a console application would work too.
public class SampleWorksheetPart : WorksheetPart
{
  public SampleWorksheetPart() {}

  public void AddPrinterSettingsPart()
  {
    // The error would occur when this method is called in the line
    // below in 10.0+ but works as expected
    // in 9.1 or earlier.
    var psPart = this.AddNewPart<SpreadsheetPrinterSettingsPart>();
  }
}

class Program
{
  static void Main(string[] args)
  {
    var fInfo = new FileInfo(@"C:\Temp\NewWorkbook.xlsx");
    // This assumes that file that fInfo references already exists
    using (var xlsx = fInfo.Open(FileMode.Open, FileAcess.ReadWrite))
    {
      using (var doc = SpreadsheetDocument.Open(xlsx, true))
      {
        var workbook = doc.WorkbookPart;
        var worksheet = workbook.Parts.FirstOrDefault(w => w.OpenXmlPart is WorksheetPart).OpenXmlPart;

        // This works fine in all versions for some reason.
        var ps = worksheet.AddNewPart<SpreadsheetPrinterSettingsPart>();
      }
    }
  }
}
``` 
**Observed**
OpenXmlPackageException: The part cannot be added here
  --> Inner exception: ArgumentOutOfRangeException: Specified argument was out of the range of valid values.

**Expected**

The part is added to the current object.

**Comment by twsouthwick** [comment] 2020-05-19 03:14
I am not able to repro the observed behavior. Can you provide a repro that I can run without any external files (if they are necessary, please include them). I tried to adapt your sample but couldn't figure out what you're doing:

```csharp
public class SampleWorksheetPart : WorksheetPart
{
    public SampleWorksheetPart() { }

    public void AddPrinterSettingsPart()
    {
        // The error would occur when this method is called in the line
        // below in 10.0+ but works as expected
        // in 9.1 or earlier.
        var psPart = this.AddNewPart<SpreadsheetPrinterSettingsPart>();
    }
}

public class Test 
{
    [Fact]
    public void Repro()
    {
        using (var ms = new MemoryStream())
        using (var doc = SpreadsheetDocument.Create(ms, SpreadsheetDocumentType.Workbook, true))
        {
            var workbook = doc.AddWorkbookPart();
            var worksheet = workbook.AddNewPart<WorksheetPart>();

            // This works fine in all versions for some reason.
            var ps = worksheet.AddNewPart<SpreadsheetPrinterSettingsPart>();
        }
    }
}
```

**Comment by rmboggs** [comment] 2020-05-19 14:49
@twsouthwick , thank you for taking the time.  Looking at the code you posted, you are half way there but you didn't add the worksheet right.  Adding parts to the worksheetPart object on the outside works as expected, however the exception occurs when trying to perform the same operation inside the object. I am able to hit this issue reliably when trying to add parts within a WorksheetPart derived class.  Please review the test code listed below and let me know if there are further questions.

This code was tested using Xunit on target framework netcoreapp2.1, although I am seeing the issue on netstandard2.0 as well.  Also, I am able to his this exception when using other parts that should be valid within the WorksheetPart class, such as VmlDrawingPart, so it is not limited to the SpreadsheetPrinterSettingsPart class that is used in the test code below.

```csharp
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using System.IO;
using Xunit;

namespace Issue720
{
  public class UnitTest720
  {
    [Fact]
    public void Bug720Test()
    {
      using (var m = new MemoryStream())
      {
        using (var doc = SpreadsheetDocument.Create(m, SpreadsheetDcumentType.Workbook, true))
        {
          var wb = doc.AddWorkbookPart();

          // Adding new worksheet part using custom worksheetpart derived class
          var ws = wb.AddNewPart<PsWorksheetPart>();

          // Call custom method to attach new part to worksheetpart. 
          // This should not throw an exception but does
          ws.AddPrinterSettingsPart();
        }
      }
    }

    private sealed class PsWorksheetPart : WorksheetPart
    {
      public PsWorksheetPart() : base() {}

      public void AddPrinterSettingsPart()
      {
        // This line is throwing the exception in question.
        var psPart = this.AddNewPart<SpreadsheetPrinterSettingsPart>();
      }
    }
  }
}
```

**Comment by twsouthwick** [comment] 2020-05-19 15:14
Thanks @rmboggs I can repro it. Let me investigate - a lot changed during 2.9.1 and 2.10.0 internally. It looks like it's not a known part so it cannot be added.... let me see why it worked in 2.9.1. This is not  a scenario I've used before, but not a fan of regressions :)

**Comment by twsouthwick** [comment] 2020-05-19 15:30
Found the issue. Need to inherit the parts; for some reason, this was changed at some point to not inherit. Fix is in review

**Comment by rmboggs** [comment] 2020-05-19 15:45
@twsouthwick Awesome, thank you.

Do you know which version this change (once review is complete and change is committed) will show up in?  Will there be a 10.2 or will this just go into the 11 work that is going on?  Fortunately, I have everything I need in 9.1 for the time being so I'm not in a hurry for a new release.  I'm just curious.

**Comment by twsouthwick** [comment] 2020-05-19 15:46
We're planning on releasing 2.11.0 soon - have to renew a cert for signing and then that'll be released

**Comment by rmboggs** [comment] 2020-05-19 15:48
Sounds good.  Again, thanks for taking the time to address.

**Closed** 2020-05-21 20:59 UTC
Labels: bug: product
