### ISSUE TITLE
PPT: The Outline default Line Width value is one pixel not the zero

### ISSUE THREAD

**Issue by lindexi** [OfficeDev/Open-XML-SDK#998] opened 2021-07-26 02:14 UTC
**Description**

I find the behavior in PowerPoint is different from the ECMA-376 document.

We can find the ECMA-376 document chapter 20.1.2.2.24 say that the Line Width is omitted, then a value of 0 is assumed.

But when we create a document with the Line Width is omitted, and the PowerPoint will show the shape Line Width as one pixel.

**Information**

- .NET Target: ALL
- DocumentFormat.OpenXml Version: ALL

**Repro**

https://github.com/lindexi/lindexi_gd/tree/173fbaf7c68023cf5064888bceeb197bd463538f/PptxDemo

```xml
  <p:sp>
    <p:nvSpPr>
      <p:cNvPr id="2" name="Rectangle 1" />
      <p:cNvSpPr />
      <p:nvPr />
    </p:nvSpPr>
    <p:spPr>
      <a:xfrm>
        <a:off x="5220072" y="1484784" />
        <a:ext cx="1440160" cy="1008112" />
      </a:xfrm>
      <a:prstGeom prst="rect"/>
      <a:ln w="0">
        <a:solidFill>
          <a:srgbClr val="565656" />
        </a:solidFill>
      </a:ln>
    </p:spPr>
  </p:sp>
```

And

```xml
  <p:sp>
    <p:nvSpPr>
      <p:cNvPr id="2" name="Rectangle 1" />
      <p:cNvSpPr />
      <p:nvPr />
    </p:nvSpPr>
    <p:spPr>
      <a:xfrm>
        <a:off x="5220072" y="1484784" />
        <a:ext cx="1440160" cy="1008112" />
      </a:xfrm>
      <a:prstGeom prst="rect"/>
      <a:ln>
        <a:solidFill>
          <a:srgbClr val="565656" />
        </a:solidFill>
      </a:ln>
    </p:spPr>
  </p:sp>
```

```csharp
        private static void ReadShape(Shape shape)
        {
            var outline = shape.ShapeProperties?.GetFirstChild<Outline>();
            if (outline != null)
            {
                var lineWidth = outline.Width;
                var emu = new Emu(lineWidth);
                var pixel = emu.ToPixel();
                Console.WriteLine($"LineWidth {pixel.Value}");
            }
            else
            {
               
            }
        }
```

**Observed**

The `outline.Width` is null

**Expected**

I dot not know how to handle the PPT behavior is different from the ECMA-376 document

**Comment by tomjebo** [comment] 2021-08-02 17:40
@lindexi, I'll send this to dochelp@microsoft.com. That's where we report Open Specification and ISO/ECMA standards issues for Office OpenXML.  It looks to me to be a specification issue that we need to investigate. I don't see a behavior note in [MS-OI29500] that addresses the default value (2.1.1211 talks about the ln element). If what you're saying is true, then there should be a note there.

**Comment by tomjebo** [comment] 2021-08-02 18:46
@lindexi I did verify the behavior in PowerPoint. It looks like it is defaulting to 1. I'll get this updated in the [MS-OI29500] (behavior notes for ISO/ECMA standard). 
Regarding how to handle the outline.Width property, I think we should consider a constraint addition to the SDK which will follow the PowerPoint behavior and assign this a default of 1. I'll have to do some more testing on supported versions of PowerPoint to see if it's just 2016/2019 or goes back to 2010 and 2013 as well.

**Comment by tomjebo** [comment] 2021-08-02 22:40
@lindexi One thing I noticed is that Word and PowerPoint don't actually add a w="1" attribute to the <ln> element upon save unless you explicitly change the UI to 1 and then save. Otherwise, it seems to leave the <ln> element untouched. I'm checking with our graphics team to see if this is just an artifact of the UI/UX and not an implication that the default is actually 1.

**Comment by lindexi** [comment] 2021-08-03 00:31
@tomjebo Thank you.

**Comment by tomjebo** [comment] 2021-08-03 00:43
@lindexi it looks like the default "1" behavior is not actually related to the w attribute. I'm still investigating but it appears that the <solidFill> element is what is causing Word and PowerPoint to default (in the UI only) to a width value of 1 pt. If you replace that with <noFill>, then it will not show any line width in the formatting dialog/panel. It will actually show only that the "No line" option is selected: 

![image](https://user-images.githubusercontent.com/4644198/127940410-95136526-19e4-41d6-b67d-acabcb6bd841.png)

**Comment by tomjebo** [comment] 2021-08-05 00:07
@lindexi, the graphics team confirmed that this behavior mimics GDI/GDI+ library behavior and has likely been in early versions of Office. I'm proposing that we add a behavior note to [MS-OI29500] 2.1.1211 (that's the section that describes our Office implementation for ISO 29500 20.1.2.2.24 ln (Outline)). 

Some notes:
A value of w="0" is not the correct way to remove the outline from a shape. To remove the outline, use the <noFill> line property. As long as there is a fill of some kind (the default fill will be <solidFill>), the outline will be drawn. When w="0" is specified in the XML or if you omit the w attribute and do not include <noFill>, the effect on Office will be to draw a 1 device unit outline on the shape. Office will also preload the Format Shape dialog with a width of "1 pt" but this will not be written to XML. 

For the SDK, we should not default the Outline class' Width property to 0 or 1. That is actually an application behavior of Office when rendering but is not persisted. For example, Office will show a width of 1 pt in the UI but it won't write anything out unless the user explicitly sets/changes that or sets/changes some other property that mandates it like <solidFill>.  Without those conditions, upon save, Office does not touch the <ln> element. So my understanding: if the w attribute is missing, calling Outline.Width should get a null object. In that case you're application should *behave* as if a shape has an outline of one device unit. But it should not persist anything to the underlying XML unless an explicit change is required. I hope this is clear.

**Comment by lindexi** [comment] 2021-08-05 00:30
@tomjebo  Thank you.

**Closed** 2021-08-05 18:04 UTC
