### ISSUE TITLE
Unable to create charts in xlsx/xlsm & pptx using OOXML & C#

### ISSUE THREAD

**Issue by PVINOD91** [OfficeDev/Open-XML-SDK#188] opened 2017-03-20 06:41 UTC
Hello,
I am recently trying to create charts in Excel & Powerpoint through OOXML SDK & C# Script. It helps to create sample bar chart, but when I tried to add some custom line & other properties, it doesn't work. please extend your help in letting me create a chart with custom defined properties. please share me your inputs and thoughts. or let me know if you need any other details from me.

**Comment by ThomasBarnekow** [comment] 2017-03-20 17:02
@PVINOD91, have you tried to:
- create the chart with whatever custom lines and other properties using Excel or PowerPoint;
- look at the Open XML mark-up produced by Excel or PowerPoint; and
- create the same mark-up using the SDK?

Otherwise, if your "issue" is related to *using* the SDK rather than some *bug* or other *shortcoming* of the SDK that should lead to a fix or enhancement of the SDK, such usage-related questions are better asked on [stackoverflow.com](http://stackoverflow.com/questions/tagged/openxml-sdk), for example. You will find more than 3.000 questions and a corresponding number of answers (although I haven't counted those) tagged with openxml or openxml-sdk.

**Comment by PVINOD91** [comment] 2017-03-21 03:48
Thanks for the Quick Reply.

I have tried to create charts in Excel or PowerPoint using OOXML & C#, but failed to achieve the final outcome (tried some solutions discussed in other internet pages, but fails) I might have missed something in script during implementation, Hence I have requested to help / the example scripts for implementing it success.

Thanks,
Vinod Pichamuthu
Honeywell Technology Solutions | TS IT

**Comment by tarunchopra** [comment] 2017-03-21 04:07
Vinod : Which version of open XML SDK are you using ? That SO forum is for 2.0 and 2.5 version which is not supported here. We support only 2.6 and above version on this forum. If you are using 2.6 or above version; have you referred unit test cases to leverage any existing test case ?




Thanks
TC | Sr. EE
On Mar 20, 2017, at 8:48 PM, PVINOD91 <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks for the Quick Reply.

I have tried to create charts in Excel or PowerPoint using OOXML & C#, but failed to achieve the final outcome (tried some solutions discussed in other internet pages, but fails) I might have missed something in script during implementation, Hence I have requested to help / the example scripts for implementing it success.

Thanks,
Vinod Pichamuthu
Honeywell Technology Solutions | TS IT

**Comment by PVINOD91** [comment] 2017-03-21 04:19
I am currently using 2.0.5022.0. But I am ready to migrate it to 2.6 or other latest version which is under your support. Please share me the latest SDK files if you have it available.

Thanks,
Vinod Pichamuthu
Honeywell Technology Solutions | TS IT

**Comment by tarunchopra** [comment] 2017-03-21 04:27
Vinod : Please refer readme ( https://github.com/OfficeDev/Open-XML-SDK ) to get package from my get. To view and serch any relevant test case; either search in code repository on github (https://github.com/OfficeDev/Open-XML-SDK) or download the latest code; open it with VS; launch test explorer to view all the existing test cases.

On Mar 20, 2017, at 9:19 PM, PVINOD91 <notifications@github.com<mailto:notifications@github.com>> wrote:

I am currently using 2.0.5022.0. But I am ready to migrate it to 2.6 or other latest version which is under your support. Please share me the latest SDK files if you have it available.

Thanks,
Vinod Pichamuthu
Honeywell Technology Solutions | TS IT

**Comment by PVINOD91** [comment] 2017-03-21 06:17
Couldn’t locate the right place to get the latest SDK files downloaded. Please route me to the right direction for SDK and test files for creating charts

Thanks,
Vinod Pichamuthu
Honeywell Technology Solutions | TS IT

**Comment by PVINOD91** [comment] 2017-03-21 06:45
Hello,
                I couldn’t open it in my VS 2010, showing this error and not letting me to go in. please let me know the way to access this project

[cid:image001.png@01D2A23C.C410AB90]

Thanks,
Vinod Pichamuthu
Honeywell Technology Solutions | TS IT

**Comment by tarunchopra** [comment] 2017-03-21 06:59
We have note tested with VS2010; please install vs2015 and test.
https://www.microsoft.com/en-us/download/details.aspx?id=48146

**Comment by PVINOD91** [comment] 2017-03-21 07:13
If I am not wrong, SDK v2.6 or above can’t be used in VS 2010, it needs VS 2015 or above. Am I right?

Thanks,
Vinod Pichamuthu
Honeywell Technology Solutions | TS IT

**Comment by tarunchopra** [comment] 2017-03-21 07:45
We have not tested 2010; is there any issue using 2015 ? Community edition 2015 is free and should work. I'll check on 2010 with team in a day or so and update the readme accordingly to avoid confusion moving forward.

**Comment by tarunchopra** [comment] 2017-03-21 07:52
One more thing; our vs2015 build is broken presently (#187). Will try to get it fixed in a day or so; sorry for the inconvenience.

**Comment by PVINOD91** [comment] 2017-03-21 08:41
Thanks for the Quick reply. Please let me know once it is fixed and ready to use. So I can test from my side

Thanks,
Vinod Pichamuthu
Honeywell Technology Solutions | TS IT

**Comment by PVINOD91** [comment] 2017-03-21 08:48
I tried in VS 2015, but the project doesn’t open to access. Please refer the attached image. Also it would be useful to update for VS 2010, because till v2.5 I could work with VS 2010, but not supporting now in higher versions.

Thanks,
Vinod Pichamuthu
Honeywell Technology Solutions | TS IT

**Comment by ThomasBarnekow** [comment] 2017-03-21 08:56
@PVINOD91, you responded that you:

> have tried to create charts in Excel or PowerPoint using OOXML & C#, but failed to achieve the final outcome.

Do you know **exactly** what the Open XML mark-up is supposed to look like? If not, the SDK will let you produce the wrong mark-up, which is why it might fail. This is why I suggested you should: 

- produce the desired outcome using **Excel** or **PowerPoint** rather than the SDK;
- look at the mark-up produced by **Excel** or **PowerPoint**; and
- reproduce that mark-up using the SDK.

Did you try **exactly** that? Or did you just try it using the SDK?

**Comment by ThomasBarnekow** [comment] 2017-03-21 09:07
@PVINOD91, how do you intend to use the SDK? Do you want to:

1. change and possibly contribute to the source code or
2. just use the SDK as it is released?

In the first case, you should really go with the flow and use recent tooling. VS2010 is no longer "recent" and will create issues for yourself and this project.

In the second case, you should really consider using the NuGet packages hosted on myget.org. To do that, look at the [Readme](https://github.com/OfficeDev/Open-XML-SDK) on the main project page and at how you can [use NuGet in Visual Studio 2010](https://github.com/paypal/sdk-core-dotnet/wiki/Using-Nuget-in-Visual-Studio-2010-&-2012).

**Comment by PVINOD91** [comment] 2017-03-21 09:07
To be honest, I did understand your completely. But I will explain what I have tried so far.


1.       I was able to create PowerPoint Presentation (Images, Copy Charts from Excel, Table & Comments) using OOXML. Success

2.       I tried to update excel (xlsx & xlsm) cells using OOXML. Success

3.       I tried to create a chart (both Chart Sheet & Chart Object) in Excel using data from an Excel Sheet, which is failed

Hence I have requested your support for making my 3rd Point Success, which will definitely be useful to many projects.

Please let me know if you could understand my problem. Also would it be possible to have a short call? so I can explain it in detail.

Thanks,
Vinod Pichamuthu
Honeywell Technology Solutions | TS IT

**Comment by PVINOD91** [comment] 2017-03-21 09:09
I just wanted to use the latest SDK as it is released, but in Visual Studio 2010 if possible.

But I had an another problem that I really needed a support for. Please refer my previous reply for understanding

Thanks,
Vinod Pichamuthu
Honeywell Technology Solutions | TS IT

**Comment by ThomasBarnekow** [comment] 2017-03-21 09:14
@PVINOD91, could you please tell me whether you tried what I suggested?

**Comment by PVINOD91** [comment] 2017-03-21 09:21
I can easily create the desired outputs using Excel Macros or other Programming languages, but I wanted to achieve it through OOXML & C#. because the project is already 90% implemented with OOXML, hence I didn’t want to achieve it through other solutions.

Please let me know if possible to have a short discussion through any medium, will talk for better understanding.

Thanks,
Vinod Pichamuthu
Honeywell Technology Solutions | TS IT

**Comment by ThomasBarnekow** [comment] 2017-03-21 10:16
@PVINOD91, I can't talk to you right now, unfortunately. 

Assuming you have created the output (e.g., Excel workbook) you desire by whatever means (manually, through VBA), did you have a look at the Open XML? Looking at the Open XML mark-up representing what you desire has been my point from my first response.

Say you have an Excel file that looks exactly as desired. If you then look at the Open XML, you will see what you have to produce using the SDK.

**Comment by PVINOD91** [comment] 2017-03-21 10:46
Say you have an Excel file that looks exactly as desired. If you then look at the Open XML, you will see what you have to produce using the SDK. – I understand this point and I have followed this so far to create PPT presentations & Excel files. But I couldn’t create XML for Charts using C# script how it looks like in an Excel file looks exactly as desired.

Hence I would need a sample script to create a Scatter XY chart / Other Charts in excel with custom line properties in using OOXML & C#. please guide

Thanks,
Vinod Pichamuthu
Honeywell Technology Solutions | TS IT

**Comment by ThomasBarnekow** [comment] 2017-03-21 12:45
@PVINOD91, I don't know what the code looks like if I don't know what Open XML mark-up I need to create. If you followed my advice, you will now have the Open XML mark-up. Can you please share that here?

I have never done what you are trying to achieve. What I am describing is an approach to getting to a solution, which often is to just construct the right objects. Thus, if you see the Open XML mark-up, you will know which objects to create.

For example, say you wanted to create a `WordprocessingDocument` with a simple paragraph that just said "Hello World!". The relevant portion of the Open XML mark-up would look like this:
```
<w:p>
  <w:r>
    <w:t>Hello World!</w:t>
  <w:r>
<w:p>
```
You'd find out that you are looking at instances of the `Paragraph`, `Run`, and `Text` classes. To create that paragraph, you would have to write something like this (and I've nested it to highlight the structure):
```
Paragraph p =
    new Paragraph(
        new Run(
            new Text("Hello World")));
```
Your mark-up will be much more complex than that. However, the point is simply that you want to construct an XML document, the elements of which directly correspond to classes provided by the very low-level Open XML SDK.

The Open XML SDK is so low-level that you could achieve the same thing using Linq to XML (and look at the [PowerTools for Open XML](https://github.com/OfficeDev/Open-Xml-PowerTools) for how this is used). So, say you have the following utility class:
```
public static class W
{
    public static readonly XNamespace = "http://schemas.openxmlformats.org/wordprocessingml/2006/main";
    public static readonly XName p = w + "p";
    public static readonly XName r = w + "r";
    public static readonly XName t = w + "t";
}
```
Using Linq to XML, you would simply write the following:
```
XElement p =
    new XElement(W.p,
        new XElement(W.r,
            new XElement(W.t, "Hello World!")));
```
Compare that again to the corresponding Open XML SDK classes:
```
Paragraph p =
    new Paragraph(
        new Run(
            new Text("Hello World")));
```
Pretty close, isn't it?

The key point is that the Open XML SDK is a very low-level SDK that allows you to work with XML mark-up. It doesn't provide any high-level abstraction. Thus, you need to know what mark-up (and which Open XML parts) you want to create and then create nested instances of the classes representing that mark-up. That nesting is achieved either when constructing an instance or by appending child elements later on.

**Comment by PVINOD91** [comment] 2017-03-21 13:11
Thanks for the detailed explanation. This is how I build nested XML structure to get my things done for PowerPoint Presentation & Excel Files update.

To create charts, I have referred this link https://msdn.microsoft.com/en-us/library/office/cc820055.aspx, which helped me to create sample bar chart without custom chart / bar properties.

But when I wanted to update the custom properties, I was able to properly build the XML markups, but the folder structure was different. Hence it was not success. (I didn’t know how the folder structure was changed, after adding XML markups for custom properties)

Please let me know if you could understand my points, otherwise I will create sample projects to differentiate both and I will forward it tomorrow

Thanks,
Vinod Pichamuthu
Honeywell Technology Solutions | TS IT

**Comment by ThomasBarnekow** [comment] 2017-03-21 14:07
@PVINOD91, what *exactly* do you mean with

> the folder structure was different. Hence it was not success. (I didn’t know how the folder structure was changed, after adding XML markups for custom properties)

Are you saying that additional parts are required for those custom properties?

Again, it is important to understand what the correct outcome looks like. If the outcome is created by adding well-defined mark-up to a single part, that is one thing. If the outcome is produced by creating multiple, interconnected parts, that obviously requires the creation and linkage of the appropriate set of parts with their individual mark-up.

For example, a very simple `WordprocessingDocument` requires just one part, the `MainDocumentPart`. If you want to use styles, you also need to add a `StyleDefinitionsPart` referenced by the `MainDocumentPart`. Numbering requires yet another part, the `NumberingDefinitionsPart`. And so on.

Are you using the [Open XML Package Editor](https://marketplace.visualstudio.com/items?itemName=ChrisRae.OpenXMLPackageEditorforVisualStudio) to view the contents of Open XML files (e.g., Excel)? This could make your life a lot easier.

One thing to note is also that you need to have a good understanding of the Open XML Specification if you want to use the Open XML SDK successfully (because it is such a low-level SDK).

BTW, it would be better to use GitHub's web interface to have these conversations. If you just respond by email, including all the previous text, your replies are not easily readable.

**Comment by PVINOD91** [comment] 2017-03-21 15:49
This sample bar chart is created by referring https://msdn.microsoft.com/en-us/library/office/cc820055.aspx
![bar1](https://cloud.githubusercontent.com/assets/26536321/24155422/292e8e8a-0e2a-11e7-982b-284f31da40ff.png)

if you could refer this image xml structure there is "chart.xml" in the location xl>drawings>charts>chart.xml 
![folderstructure1](https://cloud.githubusercontent.com/assets/26536321/24155649/ce7754da-0e2a-11e7-8383-ac61af4164a1.png)

if you could refer this image which has a simple custom property change
![bar2](https://cloud.githubusercontent.com/assets/26536321/24155762/1783677c-0e2b-11e7-8912-dbef7622b4b6.png), I just inserted title component for Y Axis.

after this custom property update, the xml folder structure changes into xl>charts>chart1.xml. please refer this image 
![folderstructure2](https://cloud.githubusercontent.com/assets/26536321/24156046/d896bff4-0e2b-11e7-80ad-e677aef5afb7.png)

this is the reason i could not make it success eventhough I build the same xml markups.

few c# script lines used for sample chart:
// Add a new drawing to the worksheet.
            DrawingsPart drawingsPart = worksheetPart.AddNewPart<DrawingsPart>();
            worksheetPart.Worksheet.Append(new DocumentFormat.OpenXml.Spreadsheet.Drawing() { Id = worksheetPart.GetIdOfPart(drawingsPart) });
            worksheetPart.Worksheet.Save();

            // Add a new chart and set the chart language to English-US.
            ChartPart chartPart = drawingsPart.AddNewPart<ChartPart>();
            chartPart.ChartSpace = new ChartSpace();
            chartPart.ChartSpace.Append(new EditingLanguage() { Val = new StringValue("en-US") });
            Drawing.Charts.Chart chart = chartPart.ChartSpace.AppendChild<Drawing.Charts.Chart>(new Drawing.Charts.Chart());

but when I use the same lines with custom properties xml markups, it is updating chart.xml in xl>drawings>charts>chart.xml but not xl>charts>chart1.xml.

so please check my detailed explanation and revert to me for further more details. thanks

**Comment by ThomasBarnekow** [comment] 2017-03-21 16:08
Are you sure that the only change you need to make is in that `ChartPart`? How did you create that example chart? in Excel? What **exactly** was the difference between the .xlsx file before and after you made that change? Were any parts added? Was any mark-up added elsewhere?

For example, if you add a single sheet with text content in the cells, this requires multiple parts.

**Comment by PVINOD91** [comment] 2017-03-21 16:37
yes I need to make changes in chart Part. maybe the chart part should be appended to another part I didn't know, instead of drawingspart. I create this example chart in excel (.xlsx). the only difference between the .xlsx file before and after I made that change was Y Axis Title Component. no other parts have been added after that. main difference I could see was the position of that chart.xml / chart1.xml file

**Comment by PVINOD91** [comment] 2017-03-21 17:14
if I add a single sheet with text content, it may need only worksheetpart>worksheet>sheetdata>row

**Comment by twsouthwick** [comment] 2017-03-21 18:56
As @ThomasBarnekow mentioned, this kind of question is much better suited for SO. This issue is not a problem with the SDK. Please repost your question there so the wider OpenXML community will see it and can help.

@tarunchopra I've requested the tag on SO to be updated to remove the version number as there is no need to limit to just 2.0 and 2.5 there. I don't have enough reputation to do it myself, so it will be peer reviewed and hopefully updated in the next few days.

**Comment by ThomasBarnekow** [comment] 2017-03-21 19:04
@PVINOD91, if you have a workbook with a single sheet and some text, e.g., "Hello World!", Excel will represent that sheet and its text using two (2) parts rather than just one. It will have one part for the sheet (e.g., `sheet1.xml`) and one part for shared strings (e.g., `sharedStrings.xml`) that is referenced by the cells.

I also did my own little test, producing an Excel workbook with a column chart (and taking a first snapshot of that) and then adding "Axis Titles" as a custom element and editing the vertical (Y) axis title ("This is my custom axis title") (and taking the second snapshot). Using the Open XML Package Editor, I looked at the package structure and the contents of those parts.

Firstly, I found out which parts reference which other parts. Using the XML file names that you would see, the important references are as follows:
```
xl/workbook.xml -> xl/worksheets/sheet1.xml -> xl/drawings/drawing1.xml -> xl/charts/chart1.xml
```
Next, I looked at `chart1.xml` in both snapshots and found that **two** `c:title` elements with children were added in the second snapshot (see below).

So, here's my `chart1.xml` that I have created with Excel 2016. The first part was not affected by adding the axis title.
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<c:chartSpace xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:c16r2="http://schemas.microsoft.com/office/drawing/2015/06/chart">
  <c:date1904 val="0"/>
  <c:lang val="en-US"/>
  <c:roundedCorners val="0"/>
  <mc:AlternateContent xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006">
    <mc:Choice Requires="c14" xmlns:c14="http://schemas.microsoft.com/office/drawing/2007/8/2/chart">
      <c14:style val="102"/>
    </mc:Choice>
    <mc:Fallback>
      <c:style val="2"/>
    </mc:Fallback>
  </mc:AlternateContent>
  <c:chart>
    <c:title>
      <c:overlay val="0"/>
      <c:spPr>
        <a:noFill/>
        <a:ln>
          <a:noFill/>
        </a:ln>
        <a:effectLst/>
      </c:spPr>
      <c:txPr>
        <a:bodyPr rot="0" spcFirstLastPara="1" vertOverflow="ellipsis" vert="horz" wrap="square" anchor="ctr" anchorCtr="1"/>
        <a:lstStyle/>
        <a:p>
          <a:pPr>
            <a:defRPr sz="1400" b="0" i="0" u="none" strike="noStrike" kern="1200" spc="0" baseline="0">
              <a:solidFill>
                <a:schemeClr val="tx1">
                  <a:lumMod val="65000"/>
                  <a:lumOff val="35000"/>
                </a:schemeClr>
              </a:solidFill>
              <a:latin typeface="+mn-lt"/>
              <a:ea typeface="+mn-ea"/>
              <a:cs typeface="+mn-cs"/>
            </a:defRPr>
          </a:pPr>
          <a:endParaRPr lang="en-US"/>
        </a:p>
      </c:txPr>
    </c:title>
    <c:autoTitleDeleted val="0"/>
    <c:plotArea>
      <c:layout/>
      <c:barChart>
        <c:barDir val="col"/>
        <c:grouping val="clustered"/>
        <c:varyColors val="0"/>
        <c:ser>
          <c:idx val="0"/>
          <c:order val="0"/>
          <c:spPr>
            <a:solidFill>
              <a:schemeClr val="accent1"/>
            </a:solidFill>
            <a:ln>
              <a:noFill/>
            </a:ln>
            <a:effectLst/>
          </c:spPr>
          <c:invertIfNegative val="0"/>
          <c:cat>
            <c:strRef>
              <c:f>Sheet1!$B$4:$B$6</c:f>
              <c:strCache>
                <c:ptCount val="3"/>
                <c:pt idx="0">
                  <c:v>First</c:v>
                </c:pt>
                <c:pt idx="1">
                  <c:v>Second</c:v>
                </c:pt>
                <c:pt idx="2">
                  <c:v>Third</c:v>
                </c:pt>
              </c:strCache>
            </c:strRef>
          </c:cat>
          <c:val>
            <c:numRef>
              <c:f>Sheet1!$C$4:$C$6</c:f>
              <c:numCache>
                <c:formatCode>General</c:formatCode>
                <c:ptCount val="3"/>
                <c:pt idx="0">
                  <c:v>100</c:v>
                </c:pt>
                <c:pt idx="1">
                  <c:v>200</c:v>
                </c:pt>
                <c:pt idx="2">
                  <c:v>300</c:v>
                </c:pt>
              </c:numCache>
            </c:numRef>
          </c:val>
          <c:extLst>
            <c:ext uri="{C3380CC4-5D6E-409C-BE32-E72D297353CC}" xmlns:c16="http://schemas.microsoft.com/office/drawing/2014/chart">
              <c16:uniqueId val="{00000000-CFFA-4E0D-B9D8-9A4CAD726C39}"/>
            </c:ext>
          </c:extLst>
        </c:ser>
        <c:dLbls>
          <c:showLegendKey val="0"/>
          <c:showVal val="0"/>
          <c:showCatName val="0"/>
          <c:showSerName val="0"/>
          <c:showPercent val="0"/>
          <c:showBubbleSize val="0"/>
        </c:dLbls>
        <c:gapWidth val="219"/>
        <c:overlap val="-27"/>
        <c:axId val="484016424"/>
        <c:axId val="484016752"/>
      </c:barChart>
      <c:catAx>
        <c:axId val="484016424"/>
        <c:scaling>
          <c:orientation val="minMax"/>
        </c:scaling>
        <c:delete val="0"/>
        <c:axPos val="b"/>
```
Here comes the first `c:title` that was inserted by adding the axis title:
```
        <c:title>
          <c:overlay val="0"/>
          <c:spPr>
            <a:noFill/>
            <a:ln>
              <a:noFill/>
            </a:ln>
            <a:effectLst/>
          </c:spPr>
          <c:txPr>
            <a:bodyPr rot="0" spcFirstLastPara="1" vertOverflow="ellipsis" vert="horz" wrap="square" anchor="ctr" anchorCtr="1"/>
            <a:lstStyle/>
            <a:p>
              <a:pPr>
                <a:defRPr sz="1000" b="0" i="0" u="none" strike="noStrike" kern="1200" baseline="0">
                  <a:solidFill>
                    <a:schemeClr val="tx1">
                      <a:lumMod val="65000"/>
                      <a:lumOff val="35000"/>
                    </a:schemeClr>
                  </a:solidFill>
                  <a:latin typeface="+mn-lt"/>
                  <a:ea typeface="+mn-ea"/>
                  <a:cs typeface="+mn-cs"/>
                </a:defRPr>
              </a:pPr>
              <a:endParaRPr lang="en-US"/>
            </a:p>
          </c:txPr>
        </c:title>
```
The following was not changed.
```
        <c:numFmt formatCode="General" sourceLinked="1"/>
        <c:majorTickMark val="none"/>
        <c:minorTickMark val="none"/>
        <c:tickLblPos val="nextTo"/>
        <c:spPr>
          <a:noFill/>
          <a:ln w="9525" cap="flat" cmpd="sng" algn="ctr">
            <a:solidFill>
              <a:schemeClr val="tx1">
                <a:lumMod val="15000"/>
                <a:lumOff val="85000"/>
              </a:schemeClr>
            </a:solidFill>
            <a:round/>
          </a:ln>
          <a:effectLst/>
        </c:spPr>
        <c:txPr>
          <a:bodyPr rot="-60000000" spcFirstLastPara="1" vertOverflow="ellipsis" vert="horz" wrap="square" anchor="ctr" anchorCtr="1"/>
          <a:lstStyle/>
          <a:p>
            <a:pPr>
              <a:defRPr sz="900" b="0" i="0" u="none" strike="noStrike" kern="1200" baseline="0">
                <a:solidFill>
                  <a:schemeClr val="tx1">
                    <a:lumMod val="65000"/>
                    <a:lumOff val="35000"/>
                  </a:schemeClr>
                </a:solidFill>
                <a:latin typeface="+mn-lt"/>
                <a:ea typeface="+mn-ea"/>
                <a:cs typeface="+mn-cs"/>
              </a:defRPr>
            </a:pPr>
            <a:endParaRPr lang="en-US"/>
          </a:p>
        </c:txPr>
        <c:crossAx val="484016752"/>
        <c:crosses val="autoZero"/>
        <c:auto val="1"/>
        <c:lblAlgn val="ctr"/>
        <c:lblOffset val="100"/>
        <c:noMultiLvlLbl val="0"/>
      </c:catAx>
      <c:valAx>
        <c:axId val="484016752"/>
        <c:scaling>
          <c:orientation val="minMax"/>
        </c:scaling>
        <c:delete val="0"/>
        <c:axPos val="l"/>
        <c:majorGridlines>
          <c:spPr>
            <a:ln w="9525" cap="flat" cmpd="sng" algn="ctr">
              <a:solidFill>
                <a:schemeClr val="tx1">
                  <a:lumMod val="15000"/>
                  <a:lumOff val="85000"/>
                </a:schemeClr>
              </a:solidFill>
              <a:round/>
            </a:ln>
            <a:effectLst/>
          </c:spPr>
        </c:majorGridlines>
```
Here comes the second `c:title` that was inserted by adding just one axis title:
```
        <c:title>
          <c:tx>
            <c:rich>
              <a:bodyPr rot="-5400000" spcFirstLastPara="1" vertOverflow="ellipsis" vert="horz" wrap="square" anchor="ctr" anchorCtr="1"/>
              <a:lstStyle/>
              <a:p>
                <a:pPr>
                  <a:defRPr sz="1000" b="0" i="0" u="none" strike="noStrike" kern="1200" baseline="0">
                    <a:solidFill>
                      <a:schemeClr val="tx1">
                        <a:lumMod val="65000"/>
                        <a:lumOff val="35000"/>
                      </a:schemeClr>
                    </a:solidFill>
                    <a:latin typeface="+mn-lt"/>
                    <a:ea typeface="+mn-ea"/>
                    <a:cs typeface="+mn-cs"/>
                  </a:defRPr>
                </a:pPr>
                <a:r>
                  <a:rPr lang="en-GB"/>
                  <a:t>This is my custom axis title</a:t>
                </a:r>
              </a:p>
            </c:rich>
          </c:tx>
          <c:overlay val="0"/>
          <c:spPr>
            <a:noFill/>
            <a:ln>
              <a:noFill/>
            </a:ln>
            <a:effectLst/>
          </c:spPr>
          <c:txPr>
            <a:bodyPr rot="-5400000" spcFirstLastPara="1" vertOverflow="ellipsis" vert="horz" wrap="square" anchor="ctr" anchorCtr="1"/>
            <a:lstStyle/>
            <a:p>
              <a:pPr>
                <a:defRPr sz="1000" b="0" i="0" u="none" strike="noStrike" kern="1200" baseline="0">
                  <a:solidFill>
                    <a:schemeClr val="tx1">
                      <a:lumMod val="65000"/>
                      <a:lumOff val="35000"/>
                    </a:schemeClr>
                  </a:solidFill>
                  <a:latin typeface="+mn-lt"/>
                  <a:ea typeface="+mn-ea"/>
                  <a:cs typeface="+mn-cs"/>
                </a:defRPr>
              </a:pPr>
              <a:endParaRPr lang="en-US"/>
            </a:p>
          </c:txPr>
        </c:title>
```
The following was not changed.
```
        <c:numFmt formatCode="General" sourceLinked="1"/>
        <c:majorTickMark val="none"/>
        <c:minorTickMark val="none"/>
        <c:tickLblPos val="nextTo"/>
        <c:spPr>
          <a:noFill/>
          <a:ln>
            <a:noFill/>
          </a:ln>
          <a:effectLst/>
        </c:spPr>
        <c:txPr>
          <a:bodyPr rot="-60000000" spcFirstLastPara="1" vertOverflow="ellipsis" vert="horz" wrap="square" anchor="ctr" anchorCtr="1"/>
          <a:lstStyle/>
          <a:p>
            <a:pPr>
              <a:defRPr sz="900" b="0" i="0" u="none" strike="noStrike" kern="1200" baseline="0">
                <a:solidFill>
                  <a:schemeClr val="tx1">
                    <a:lumMod val="65000"/>
                    <a:lumOff val="35000"/>
                  </a:schemeClr>
                </a:solidFill>
                <a:latin typeface="+mn-lt"/>
                <a:ea typeface="+mn-ea"/>
                <a:cs typeface="+mn-cs"/>
              </a:defRPr>
            </a:pPr>
            <a:endParaRPr lang="en-US"/>
          </a:p>
        </c:txPr>
        <c:crossAx val="484016424"/>
        <c:crosses val="autoZero"/>
        <c:crossBetween val="between"/>
      </c:valAx>
      <c:spPr>
        <a:noFill/>
        <a:ln>
          <a:noFill/>
        </a:ln>
        <a:effectLst/>
      </c:spPr>
    </c:plotArea>
    <c:plotVisOnly val="1"/>
    <c:dispBlanksAs val="gap"/>
    <c:showDLblsOverMax val="0"/>
  </c:chart>
  <c:spPr>
    <a:solidFill>
      <a:schemeClr val="bg1"/>
    </a:solidFill>
    <a:ln w="9525" cap="flat" cmpd="sng" algn="ctr">
      <a:solidFill>
        <a:schemeClr val="tx1">
          <a:lumMod val="15000"/>
          <a:lumOff val="85000"/>
        </a:schemeClr>
      </a:solidFill>
      <a:round/>
    </a:ln>
    <a:effectLst/>
  </c:spPr>
  <c:txPr>
    <a:bodyPr/>
    <a:lstStyle/>
    <a:p>
      <a:pPr>
        <a:defRPr/>
      </a:pPr>
      <a:endParaRPr lang="en-US"/>
    </a:p>
  </c:txPr>
  <c:printSettings>
    <c:headerFooter/>
    <c:pageMargins b="0.75" l="0.7" r="0.7" t="0.75" header="0.3" footer="0.3"/>
    <c:pageSetup/>
  </c:printSettings>
</c:chartSpace>
```

**Comment by PVINOD91** [comment] 2017-03-22 03:39
Thanks for the very detailed explanation. I knew it was not SDK problem, it was because I was unaware how to build the xml markups. please route me to the right team. so they can help to get some more ideas in using it effectively

**Comment by PVINOD91** [comment] 2017-03-22 04:42
[Open XML.zip](https://github.com/OfficeDev/Open-XML-SDK/files/860354/Open.XML.zip)
Attached Zip file has two excel files and a PowerPoint to briefly explain the problem.

Excel File "No custom changes.xlsx" was created by C# script & OOXML, referring https://msdn.microsoft.com/en-us/library/office/cc820055.aspx

after creating this excel file, I manually opened the file and inserted "Y Axis Title" and reviewed the package structure. surprised and it was a complete change in the package structure.

Hence I would like to if I need to introduce other parts instead of "drawingpart" to append the chartpart.
in simple, please explain how to customize the package structure

**Comment by ThomasBarnekow** [comment] 2017-03-22 07:40
@PVINOD91, as also @twsouthwick said, stackoverflow.com would be the place to go for asking your **how-to** questions. As you rightly said, this is **not** an SDK **issue**.

Some last comments ...

- Note that the Open-XML-SDK and Excel (in particular) might produce output that **looks** different to the casual user but in fact is totally in line with the Open XML specification. Excel will also create certain parts (e.g., for properties and styles) that you would have to create explicitly using the SDK.

- In my previous, lengthy post, I said that I only found changes in the chart part. Did you look at the changes I identified and compared those to what you have done to create axis titles (note the plural) in your code? Did you use the Open XML Package Editor as I suggested?

- Please do have a look at the Open XML Specification or other sources to understand a little more about the structure and content of what you are trying to create. As long as you are using the Open XML SDK, you must first understand WHAT you need to produce and only then can you know HOW top produce it using the SDK.

**Comment by PVINOD91** [comment] 2017-03-29 05:18
Hello again, I reached out stackoverflow.com for this question. It didn't help me yet. I am suspecting it may be because of the version of Open XML (version 2.5), Currently I use. Hence, could you please share me the latest Open XML SDK version 2.6 or above (latest) ?, so I could check if I can get that feature success and some additional features for my project.

**Comment by ThomasBarnekow** [comment] 2017-03-29 05:58
This site (GitHub) and myget.org (see README.md) are meant to share exactly what you are asking for. You can build whichever version from source using this repo (or a fork if you wish to make changes) or you can install a NuGet package with the latest and greatest already built from myget.org as described in the README.

**Comment by PVINOD91** [comment] 2017-03-29 08:59
Thanks.. I was told that the last build had some problems two weeks ago, so just wanted to confirm

Hence, Please confirm the latest SDK update has no problems in using it.

**Comment by ThomasBarnekow** [comment] 2017-03-29 14:36
I can only say that I am using the latest version (`2.7.2-vnext0027`) of the `DocumentFormat.OpenXml` package hosted on [myget.org](https://dotnet.myget.org/gallery/open-xml-sdk) without problems so far.

Using the NuGet package removes the need to build from source, which now requires Visual Studio 2017 if you want to build the latest and greatest.

**Comment by twsouthwick** [comment] 2017-03-29 15:26
@PVINOD91 If you have a specific issue, we can investigate it. Can you give context to your question? ie what issues are you referring to? If there is an issue that you are encountering, please give full context for the issue and what you are seeing compared to what you are expecting.

Also, if you add the link for the SO question, then we can respond there for questions on usage rather than issues with the project. I spent a few minutes looking and couldn't find the issue you posted.

**Comment by ThomasBarnekow** [comment] 2017-05-05 16:39
@twsouthwick and @tomjebo, I think we can close this as a non-issue (but rather a how-to question).

**Comment by twsouthwick** [comment] 2017-05-05 16:42
Sounds good. @PVINOD91  please let us know if you run into any SDK related issues while working on this.

**Closed by twsouthwick** 2017-05-05 16:42 UTC

**Comment by PVINOD91** [comment] 2017-05-08 03:15
Please close this ticket. Sorry for the late notice. Now I could able to successfully get my things done using Open XML SDK. I will definitely reach out to you for any other Open XML SDK issues
