### ISSUE TITLE
Complex mergefields not working

### ISSUE THREAD

**Issue by Question101** [OfficeDev/Open-XML-SDK#275] opened 2017-10-27 13:46 UTC
Hello 

I'm just wondering if anyone has seen this issue before. We are using Open XML SDK version 2.5 to do some document merging in our application, and as standard is fine, however, if the Mergefield contains any sort of formatting in the .DOCX, eg bold, italics font change,  Word is automatically converting it, from a simple mergefield to a complex mergefield.

When we run our code we’re parsing the XML for Mergefield XML Elements, but it’s not finding the complex mergefields, so the merge is not working. It just brings over the field in plain text eg [[CO_COMPANYNAME]] as opposed to the actual data.

Thanks

**Comment by twsouthwick** [comment] 2017-10-30 20:20
Can you provide a repro? Also, have you checked to see if it repros on 2.7.2, the latest released version?

**Comment by Question101** [comment] 2017-11-01 11:36
Hello. Thanks for the response. We are just building some sample code now and going to try with 2.7.2 and then will post an update.

**Comment by VenkataSri** [comment] 2017-11-02 08:49
Hi, I have a problem with OpenXML.  I have created a table using rowspan and colspan.  but while converting in Docx the display is getting changed.  I am enclosing the HTML and screenshot of the output.  If someone has any solution that would be a great help.

Thank you,
Venkata
<img width="414" alt="table_format" src="https://user-images.githubusercontent.com/33311194/32317103-b3caa3f2-bfd8-11e7-95cd-b5886907c593.png">

**Comment by Question101** [comment] 2017-11-02 08:54
Hello, sorry but can you please open your own new thread I'm waiting for some info for our actual problem to add to here. Thanks

**Comment by VenkataSri** [comment] 2017-11-02 08:55
oh am sorry.. I will do it..
thanks

**Comment by twsouthwick** [comment] 2017-11-12 01:13
@Question101 The example you've supplied is quite large and I can't see what the issue is among all the various subs. A repro would be most helpful in the form of a unit test with a very targeted example:

```vb
' Set up the documents
' Do something to them
' Assert what should be seen
```

For help, please take a look at the unit tests in the project.

**Comment by Misiu** [comment] 2017-11-13 12:16
@twsouthwick I have same problem with merge field's.
When I iterate over `SimpleField` fields I sometimes get other number of fields than I have mergeFields in my document.
I've searched a bit and I noticed that this is because of different types of merge fields: https://social.msdn.microsoft.com/Forums/office/en-US/ef940df1-253c-499c-8dba-92107c3a34d7/programatically-fill-mergefields-and-manually-populate-bookmarks-using-open-xml-sdk?forum=oxmlsdk#196307ea-99ce-4c41-996f-902ac25ca5fe

In example document:
![snap 2017-11-13 at 13 01 20](https://user-images.githubusercontent.com/1741838/32724730-c5483476-c872-11e7-8add-759bab7e7770.png)
that has this document.xml s a source:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" mc:Ignorable="w14 wp14">
	<w:body>
		<w:p w:rsidR="001B546D" w:rsidRDefault="00926166">
			<w:r>
				<w:fldChar w:fldCharType="begin"/>
			</w:r>
			<w:r>
				<w:instrText xml:space="preserve"> MERGEFIELD  Imie  \* MERGEFORMAT </w:instrText>
			</w:r>
			<w:r>
				<w:fldChar w:fldCharType="separate"/>
			</w:r>
			<w:r w:rsidR="000A2787">
				<w:rPr>
					<w:noProof/>
				</w:rPr>
				<w:t>«Imie»</w:t>
			</w:r>
			<w:r>
				<w:rPr>
					<w:noProof/>
				</w:rPr>
				<w:fldChar w:fldCharType="end"/>
			</w:r>
			<w:r w:rsidR="003D76CB">
				<w:t xml:space="preserve"> </w:t>
			</w:r>
			<w:r>
				<w:fldChar w:fldCharType="begin"/>
			</w:r>
			<w:r>
				<w:instrText xml:space="preserve"> MERGEFIELD  Wiek  \* MERGEFORMAT </w:instrText>
			</w:r>
			<w:r>
				<w:fldChar w:fldCharType="separate"/>
			</w:r>
			<w:r w:rsidR="003D76CB">
				<w:rPr>
					<w:noProof/>
				</w:rPr>
				<w:t>«Wiek»</w:t>
			</w:r>
			<w:r>
				<w:rPr>
					<w:noProof/>
				</w:rPr>
				<w:fldChar w:fldCharType="end"/>
			</w:r>
		</w:p>
		<w:p w:rsidR="000A2787" w:rsidRDefault="00926166">
			<w:r>
				<w:fldChar w:fldCharType="begin"/>
			</w:r>
			<w:r>
				<w:instrText xml:space="preserve"> MERGEFIELD  Nazwisko  \* MERGEFORMAT </w:instrText>
			</w:r>
			<w:r>
				<w:fldChar w:fldCharType="separate"/>
			</w:r>
			<w:r w:rsidR="000A2787">
				<w:rPr>
					<w:noProof/>
				</w:rPr>
				<w:t>«Nazwisko»</w:t>
			</w:r>
			<w:r>
				<w:rPr>
					<w:noProof/>
				</w:rPr>
				<w:fldChar w:fldCharType="end"/>
			</w:r>
		</w:p>
		<w:p w:rsidR="0007196D" w:rsidRDefault="00926166">
			<w:pPr>
				<w:rPr>
					<w:noProof/>
				</w:rPr>
			</w:pPr>
			<w:r>
				<w:fldChar w:fldCharType="begin"/>
			</w:r>
			<w:r>
				<w:instrText xml:space="preserve"> MERGEFIELD  BARCODE  \* MERGEFORMAT </w:instrText>
			</w:r>
			<w:r>
				<w:fldChar w:fldCharType="separate"/>
			</w:r>
			<w:r w:rsidR="000A2787">
				<w:rPr>
					<w:noProof/>
				</w:rPr>
				<w:t>«BARCODE»</w:t>
			</w:r>
			<w:r>
				<w:rPr>
					<w:noProof/>
				</w:rPr>
				<w:fldChar w:fldCharType="end"/>
			</w:r>
		</w:p>
		<w:p w:rsidR="00926166" w:rsidRDefault="00926166">
			<w:pPr>
				<w:rPr>
					<w:noProof/>
				</w:rPr>
			</w:pPr>
		</w:p>
		<w:p w:rsidR="00926166" w:rsidRDefault="00926166">
			<w:pPr>
				<w:rPr>
					<w:noProof/>
				</w:rPr>
			</w:pPr>
			<w:r>
				<w:rPr>
					<w:noProof/>
				</w:rPr>
				<w:fldChar w:fldCharType="begin"/>
			</w:r>
			<w:r>
				<w:rPr>
					<w:noProof/>
				</w:rPr>
				<w:instrText xml:space="preserve"> MERGEFIELD  Test  \* MERGEFORMAT </w:instrText>
			</w:r>
			<w:r>
				<w:rPr>
					<w:noProof/>
				</w:rPr>
				<w:fldChar w:fldCharType="separate"/>
			</w:r>
			<w:r>
				<w:rPr>
					<w:noProof/>
				</w:rPr>
				<w:t>«Test»</w:t>
			</w:r>
			<w:r>
				<w:rPr>
					<w:noProof/>
				</w:rPr>
				<w:fldChar w:fldCharType="end"/>
			</w:r>
			<w:bookmarkStart w:id="0" w:name="_GoBack"/>
			<w:bookmarkEnd w:id="0"/>
		</w:p>
		<w:sectPr w:rsidR="00926166">
			<w:pgSz w:w="11906" w:h="16838"/>
			<w:pgMar w:top="1417" w:right="1417" w:bottom="1417" w:left="1417" w:header="708" w:footer="708" w:gutter="0"/>
			<w:cols w:space="708"/>
			<w:docGrid w:linePitch="360"/>
		</w:sectPr>
	</w:body>
</w:document>
```
Inside Word I see 5 fields, but inside C# I get none:
`objMainDoc.Descendants<SimpleField>().ToList();`

this is true because I have no fldSimple.

I'm using this blog as a source: http://www.emoreau.com/Entries/Articles/2011/03/Using-OpenXML-to-fill-a-Word-document-from-a-Net-application.aspx

Probably complex merge fields must be treated differently, but till now I didn't found an option to do it with Open-XML.

This works:

```
<w:p w:rsidR="001B546D" w:rsidRDefault="00926166">
	<w:fldSimple w:instr=" MERGEFIELD  Name  \* MERGEFORMAT ">
		<w:r w:rsidR="000A2787">
			<w:rPr>
				<w:noProof/>
			</w:rPr>
			<w:t>«Name»</w:t>
		</w:r>
	</w:fldSimple>
	<w:r w:rsidR="003D76CB">
		<w:t xml:space="preserve"> </w:t>
	</w:r>
	<w:fldSimple w:instr=" MERGEFIELD  Age  \* MERGEFORMAT ">
		<w:r w:rsidR="003D76CB">
			<w:rPr>
				<w:noProof/>
			</w:rPr>
			<w:t>«Age»</w:t>
		</w:r>
	</w:fldSimple>
</w:p>
```
this doesn't work:
```
<w:p w:rsidR="001B546D" w:rsidRDefault="00926166">
	<w:r>
		<w:fldChar w:fldCharType="begin"/>
	</w:r>
	<w:r>
		<w:instrText xml:space="preserve"> MERGEFIELD  Name  \* MERGEFORMAT </w:instrText>
	</w:r>
	<w:r>
		<w:fldChar w:fldCharType="separate"/>
	</w:r>
	<w:r w:rsidR="000A2787">
		<w:rPr>
			<w:noProof/>
		</w:rPr>
		<w:t>«Name»</w:t>
	</w:r>
	<w:r>
		<w:rPr>
			<w:noProof/>
		</w:rPr>
		<w:fldChar w:fldCharType="end"/>
	</w:r>
	<w:r w:rsidR="003D76CB">
		<w:t xml:space="preserve"> </w:t>
	</w:r>
	<w:r>
		<w:fldChar w:fldCharType="begin"/>
	</w:r>
	<w:r>
		<w:instrText xml:space="preserve"> MERGEFIELD  Age  \* MERGEFORMAT </w:instrText>
	</w:r>
	<w:r>
		<w:fldChar w:fldCharType="separate"/>
	</w:r>
	<w:r w:rsidR="003D76CB">
		<w:rPr>
			<w:noProof/>
		</w:rPr>
		<w:t>«Age»</w:t>
	</w:r>
	<w:r>
		<w:rPr>
			<w:noProof/>
		</w:rPr>
		<w:fldChar w:fldCharType="end"/>
	</w:r>
</w:p>
```

**Comment by ThomasBarnekow** [comment] 2017-11-13 15:37
This is not an issue with the SDK but rather with the Open XML markup. The original post also mentions changes made by Word, which turns simple into complex fields, which entitely changes the algorithm required to deal with these fields.

The Open XML SDK is a low-level API that lets you work with the Open XML markup directly, without any abstraction whatsoever. The only thing it adds on top of using Linq for XML for working with the markup (as done by the PowerTools for Open XML) are strongly typed classes. But those simply reflect the markup 1:1. Therefore, when using the Open XML SDK, you must know exactly what markup you have to create or expect.

Unfortunately, Open XML is very complex. The specification has a couple thousand pages, for example. While you don‘t need to read it all, you will have to familiarize yourselves with at least the markup that is relevant for your application. You could also have a look at the PowerTools for Open XML, which provide solutions and examples for a good number of use cases, such as working with fields. You will also see how Linq for XML is used to create the markup and likely notice how structurally similar this is to using the Open XML SDK. You will see that you often have to go to great lengths for stuff that is extremely easy when using the Word object model, e.g., in VBA (but also orders of magnitude slower).

**Comment by Question101** [comment] 2017-11-13 15:50
Hello. Thanks for the comments. I will point out to our chap about 'markups' Thomas.

@twsouthwick What stage were you getting a file access error? The example was specifically made for this forum and Microsoft as requested. It generates two documents. A good one and a bad one. Microsoft were able to see the error and pointed out that someone here may understand why it was happening?

Thanks

**Comment by Misiu** [comment] 2017-11-13 19:20
@ThomasBarnekow thank You for reply. I have exact same issue. Simple fields change to complex. The only thing I've added was new line between two simple fields.
I have version with simple fields working fine, complex fields are...more complex :)

**Comment by ThomasBarnekow** [comment] 2017-11-17 16:52
@Misiu I would guess that in your situation it is also Word that turns those simple fields into complex fields. Correct? If so, this is not an Open XML SDK issue.

You have obviously produced correct Open XML markup that Word also understood. However, Word then decided to persist those fields using complex field markup, which is also correct Open XML markup. And there is unfortunately no other way than to deal with the markup produced by Word.

**Comment by twsouthwick** [comment] 2017-11-17 16:54
Thanks @ThomasBarnekow. @Misiu as this is not an issue with the Open XML SDK, I'm going to close this. Please ask questions on StackOverflow, but if you feel like this issue is with the SDK, please reopen.

**Closed by twsouthwick** 2017-11-17 16:54 UTC
Labels: bug, needs-repro
