### ISSUE TITLE
OpenXml add numerous assemblies to the binary output directory under VS2017

### ISSUE THREAD

**Issue by PatrickRyder** [OfficeDev/Open-XML-SDK#412] opened 2018-02-28 10:59 UTC
Is this a:
- [X] Issue with the OpenXml library
- [] Question on library usage

I hesitate to describe this as an issue.  It is perhaps more of a question.  I apologise for not turning to StackOverflow, but I find the site to be elitist and unapproachable unless you have a perfect textbook question.

**Description**

I have recently migrated a WPF project from Visual Studio 2015 to 2017.  I did this manually (i.e. I created a new empty WPF project and re-added all files manually).  Now I have done this, OpenXml seems to deploy **loads** more assemblies into my project output directory.

**Observed**

I no longer have Visual Studio 2015 installed and am reluctant to try to put it back alongside 2017, but, checking my project history, I can see that OpenXml did not add these extra assemblies in 2015.

**Expected**

I would expect the behaviour to be the same under Visual Studio 2017.  These extra assemblies double the size of the binary transfer I have to do to deploy the code to the client's network.

Is there any way I can stop OpenXml adding these extra assemblies to my binary output directory?

![extra assemblies](https://user-images.githubusercontent.com/13526323/36784118-2b4e93bc-1c76-11e8-9363-911f32d6386f.png)

**Comment by 0xfeeddeadbeef** [comment] 2018-02-28 12:53
Probably related to #401.

**Comment by twsouthwick** [comment] 2018-02-28 20:28
Yeah, this is a duplicate of #401 which is not something we can do much about unfortunately. Which version of .NET are you targeting?

**Comment by twsouthwick** [comment] 2018-02-28 20:36
Also, which version of the DocumentFormat.OpenXml SDK did you use in your previous project vs now?

**Comment by twsouthwick** [comment] 2018-03-05 20:22
@PatrickRyder I'm going to close this as this is expected behavior. You probably changed the version of the SDK you're using between the two projects. We target .NET Standard now and thus end up bringing in some facades (small assemblies that just forward types to other assemblies). There is work on an IL tree shaker (aka linker) that will hopefully help with this, but for now, you'll just need to include them (or use an earlier version of the SDK).

**Closed by twsouthwick** 2018-03-05 20:22 UTC
