### ISSUE TITLE
Provide official SDK in chocolatey, NuGet, OneGet

### ISSUE THREAD

**Issue by diimdeep** [OfficeDev/Open-XML-SDK#89] opened 2016-04-10 10:25 UTC
Didn't find any, in 2016 devs should be able to install that kind of stuff from cli.

**Comment by wldevries** [comment] 2016-04-20 07:50
duplicate of #2

**Comment by avishnyakov** [comment] 2016-05-19 05:47
+1

**Closed** 2016-12-16 22:29 UTC
