### ISSUE TITLE
Operation is not supported.

### ISSUE THREAD

**Issue by bijiasuo2006** [OfficeDev/Open-XML-SDK#64] opened 2015-11-02 12:27 UTC
Hi,

Below is the inner exception, seems Mono's DeflateStream not support something.

```
  at System.IO.Compression.DeflateStream.get_Length () [0x00000] in /private/tmp/source-mono-mac-4.0.0-branch-c5sr5/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.0.5/mcs/class/System/System.IO.Compression/DeflateStream.cs:297 
  at System.IO.Packaging.ZipWrappingStream.get_Length () [0x0004e] in <filename unknown>:0 
  at OpenXmlPowerTools.PtOpenXmlExtensions.GetXDocument (DocumentFormat.OpenXml.Packaging.OpenXmlPart part) [0x0001f] in /Users/Edison/Developer/Source/dotnet/open-xml-powertools/OpenXmlPowerTools/PtOpenXmlUtil.cs:54 
```

Cheers,
## 

Edison

**Comment by EricWhiteDev** [comment] 2015-11-02 13:58
Hi,

Can you kindly attach the document that the SDK fails to open?

**Comment by eliu03** [comment] 2015-11-03 08:41
Hi,
All the files in this folder https://github.com/OfficeDev/Open-Xml-PowerTools/tree/vNext/OpenXmlPowerToolsExamples/WmlToHtmlConverter01 have problem, it seems like not caused by special file.

Thanks,
--
Edison

**Comment by Numpsy** [comment] 2016-01-22 16:36
i get loads of these errors when trying to run the SDK unit tests on Mono/OSX. e.g.

```
DocumentFormat.OpenXml.Tests.MarkupCompatibilityTest.NonIgnored_UnknownAttribute_O12Mode [FAIL]
      System.NotSupportedException : Specified method is not supported.
      Stack Trace:
           at System.IO.Compression.DeflateStream.get_Length () <0x5a59a78 + 0x0001f> in <filename unknown>:0 
           at System.IO.Packaging.ZipWrappingStream.get_Length () <0x5a59950 + 0x000fe> in <filename unknown>:0 
```

Debugging it, inside ZipWrappingStream, we have

```
        // For some strange reason, if the package FileAccess == Read,
        // then can't get length from the stream.  Not supported.
        // The workaround - write the stream to a memory stream, then return the length of the
        // memory stream.
        public override long Length
        {
            get {
                if (_packageFileAccess == FileAccess.Read)
                {
                    using (MemoryStream ms = new MemoryStream())
                    using (Stream zs = _zipArchiveEntry.Open())
                    {
                        CopyStream(zs, ms);
                        return ms.Length;
                    }
                }
                else
                    return _baseStream.Length;
            }
        }
```

But in these test cases _packageFileAccess is ReadWrite, so it calls _baseStream.Length (where _baseStream is a DeflateStream, whose Length property is apparently supposed to throw according to the MSDN),

**Comment by Numpsy** [comment] 2016-01-25 18:31
For a little more info, the unit tests get a lot of these errors from OpenXMLPart.LoadDOMTree(), which it seems only wants to know if there is data in the stream rather than what the length is.
Not sure if there is anything that can be changed to work around the issue? (maybe decompress the data and Load the Part from that? Doesn't seem ideal to read all the data to work out the length and then read it again to process it though!)

**Comment by EricWhiteDev** [comment] 2016-01-26 00:45
Thanks, good information to know.

It may be desirable to modify the API for System.IO.Packaging a little bit.  The above hack, which I wrote when re-writing System.IO.Packaging is certainly less than ideal.  In the end, I left that hack in there because a) parts are small, so overhead is not too bad, and b) testing indicated that the perf of the new System.IO.Packaging was within 5% of the old one, sometimes faster, sometimes slower.

In March, I am scheduled to do one more round of cleanup on System.IO.Packaging.  We're going to remove unused parts of the assembly, document the new, reduced API of System.IO.Packaging,  I think it would be fine to add a new property, HasData, which will return whether there is content in the part or not.  We can then get rid of the above hack.

**Comment by Numpsy** [comment] 2016-01-26 11:57
Hmm, might it be possible for ZipWrappingStream.Length to make use of _zipArchiveEntry.Length in the case where the archive mode is ZipArchiveMode.Read, rather than copying the stream?

**Comment by EricWhiteDev** [comment] 2016-01-27 13:29
I seem to recall trying that.  I worked on this issue for a bit of time before resorting to the hack.

**Comment by Numpsy** [comment] 2016-03-02 14:12
A little more fishing around in some test failures (e.g. T131_String_OpenOrCreate_ReadWrite_Star ) shows up another possible Mono issue.

Seems that code along the lines of

```
string _path = Path.Combine(Directory.GetCurrentDirectory(), "Temp-16ab1efb9254430987adc092eeb60c63.docx");

var _containerStream = new FileStream(_path, FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.ReadWrite);

var zipArchive = new ZipArchive(_containerStream, ZipArchiveMode.Update, true, Encoding.UTF8);

var firstEntry = zipArchive.Entries [0].Open ();

using (StreamWriter sw = new StreamWriter(firstEntry))
{
    sw.Write("TEST");
}
```

Will manage to write to the stream on MS.Net, but will throw a 'Stream is not writeable' exception on Mono (looks like the stream returned from Open is a DeflateStream in decompress mode, which you can't write to).

**Comment by EricWhiteDev** [comment] 2016-03-03 14:13
This is going to require some research.  I am currently putting together the next version of System.IO.Packaging for COREFX, so is an opportune time to dig in.  I'll see what I find out...

**Comment by Numpsy** [comment] 2016-03-03 20:29
I put what I found in a Mono bug: https://bugzilla.xamarin.com/show_bug.cgi?id=39282

I'm thinking that Mono just isn't handling streams in update mode archives correctly, but i'm still getting to grips with how the flags and modes work, so it'll be nice to get comment from someone who knows. 

I see 23 failures when running the Packaging tests on the current Mono Master/Linux, with most of those down to the stream length/read only issues mentioned here. There are also a couple of instances of 'PackageRelationship target must be relative URI if TargetMode is Internal', which I haven't looked at).

**Comment by terodelarosa** [comment] 2016-04-26 09:03
Hello and thank you for the effort on making the SDK work on Mono. Sadly, this is the same error that I'm getting after having solved [this one](https://github.com/OfficeDev/Open-XML-SDK/issues/74) by updating to mono 4.4 alpha where it was fixed. I'll be following the issue hoping to get this working some day.

**Comment by miguelzf** [comment] 2016-06-13 23:25
Hello

I'm trying the TextReplacer example. All the test doc's fail with the following exception:

Unhandled Exception:
System.NotSupportedException: Specified method is not supported.
  at System.IO.Compression.DeflateStream.get_Length () <0x407e0770 + 0x00017> in <filename unknown>:0 
  at System.IO.Packaging.ZipWrappingStream.get_Length () <0x407e0640 + 0x0010b> in <filename unknown>:0 
  at OpenXmlPowerTools.PtOpenXmlExtensions.GetXDocument (DocumentFormat.OpenXml.Packaging.OpenXmlPart part) [0x00064] in /mnt/work/citiusadmin/Open-Xml-PowerTools/OpenXmlPowerTools/PtOpenXmlUtil.cs:67 
  at OpenXmlPowerTools.RevisionAccepter.PartHasTrackedRevisions (DocumentFormat.OpenXml.Packaging.OpenXmlPart part) [0x00002] in /mnt/work/citiusadmin/Open-Xml-PowerTools/OpenXmlPowerTools/RevisionAccepter.cs:1478 
  at OpenXmlPowerTools.RevisionAccepter.HasTrackedRevisions (DocumentFormat.OpenXml.Packaging.WordprocessingDocument doc) [0x00007] in /mnt/work/citiusadmin/Open-Xml-PowerTools/OpenXmlPowerTools/RevisionAccepter.cs:1496 
  at OpenXmlPowerTools.TextReplacer.SearchAndReplace (DocumentFormat.OpenXml.Packaging.WordprocessingDocument wordDoc, System.String search, System.String replace, Boolean matchCase) [0x00002] in /mnt/work/citiusadmin/Open-Xml-PowerTools/OpenXmlPowerTools/TextReplacer.cs:239 
  at OpenXmlPowerTools.Program.Main (System.String[] args) [0x0002d] in /mnt/work/citiusadmin/Open-Xml-PowerTools/OpenXmlPowerToolsExamples/TextReplacer02/TextReplacer02.cs:29

**Comment by tritao** [comment] 2016-06-27 16:02
We've put some more fixes in place in Mono that should help some of the problems mentioned in this issue. Please try the latest System.IO.Compression assembly from Mono and report any problems left so we can get them fixed.

**Comment by Numpsy** [comment] 2016-06-27 18:43
I gave it a go, and put some info about some issues I saw in the bugzilla entry at https://bugzilla.xamarin.com/show_bug.cgi?id=39282 (some of which relate to this problem, and an extra one that might be a separate bug in SharpCompress)

**Comment by Numpsy** [comment] 2016-06-29 15:26
Right, using Mono master as of this morning, I see various extra operation not supported errors from the Packaging tests, which have different call stacks that before. e.g.

```
System.IO.Packaging.Tests.Tests.T002_IterateParts [FAIL]
      System.NotSupportedException : Specified method is not supported.
      Stack Trace:
           at System.IO.Compression.DeflateStream.get_Length () <0x10be0f230 + 0x00025> in <filename unknown>:0 
           at System.IO.Compression.ZipArchiveEntryStream.get_Length () <0x10be0f210 + 0x0001a> in <filename unknown>:0 
           at System.IO.Packaging.ZipWrappingStream.get_Length () <0x10be0f0c0 + 0x00126> in <filename unknown>:0 
           at System.Xml.XmlReader.CalcBufferSize (System.IO.Stream input) <0x10bdf8510 + 0x0003a> in <filename unknown>:0 
           at System.Xml.XmlTextReaderImpl.InitStreamInput (System.Uri baseUri, System.String baseUriStr, System.IO.Stream stream, System.Byte[] bytes, System.Int32 byteCount, System.Text.Encoding encoding) <0x10bdf7e90 + 0x0019d> in <filename unknown>:0 
```


Looking at it, it seems that other changes in Mono master have caused more instances of the issue.
For example, the test

```
public static void Main(string[] args)
{
	var fileStream = new FileStream("monoTest.zip", FileMode.Open, FileAccess.ReadWrite, FileShare.ReadWrite);
	var zipArchive = new ZipArchive(fileStream, ZipArchiveMode.Update);

	var firstStream = zipArchive.Entries[0].Open();

	var xmlReader = System.Xml.XmlReader.Create(firstStream);
}
```

completes on Mono 4.4.0, but throws a not supported error on Master. Looks like XmlReader is querying the streams itself, and that causes the error previously seen by the SDK.

**Comment by tritao** [comment] 2016-07-01 14:06
@Numpsy feel free to give it another try with latest master.

**Comment by Numpsy** [comment] 2016-07-01 16:13
Right, good news. Using the vNext branch of the SDK and the current master branch of Mono:

The System.IO.Packaging tests get 4 failures, where there were 23 before.
The DocumentFormat.OpenXML tests get 264 failures, when the were ~400 before.

The 'Operation is not supported' errors seem to have all gone :-)

Also, a big chunk of those other failures are down to path issues when running on OSX/Linux which already have open pull requests. For example, the changes in pull#80 drop that to 187 failures.

I'll have a look at the other issues when I get a chance, and open other issues if needed.

**Comment by davideloper** [comment] 2016-12-19 10:05
I think this problem is not solved yet:
PackageRelationship target must be relative URI if TargetMode is Internal

This happens on mono, including system.io.packaging (from net.standard) with OpenXmlSDK.
Has maybe someone already resolved this bug?

**Comment by twsouthwick** [comment] 2017-11-17 03:48
@davideloper The issue you are seeing is a separate issue that is fixed with https://github.com/OfficeDev/Open-XML-SDK/pull/267. Since the original issue described here is fixed, I'm closing this issue.

**Closed by twsouthwick** 2017-11-17 03:48 UTC
