### ISSUE TITLE
How to add custom attribute into Presentation document

### ISSUE THREAD

**Issue by prostovasya** [OfficeDev/Open-XML-SDK#127] opened 2016-11-24 04:24 UTC
Hi everyone,

I tried to add a custom attribute into .pptx document. I did it, but when I saved the document from PowerPoint my attribute disappeared.

How do I preserve my custom attributes even after pptx is saved. Can I use custom XML part to store only attributes specific to each content documents? Any code samples will be helpful.

Excel has Extensions, that allow Excel convert roundtrip custom elements and are designed (as far as I can make out) for storing application specific data. 
May be there is a way resolve my issue using Extensions  ?

Here is my code: 

```
namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            var file = @"C:\temp\123.pptx";

            using (PresentationDocument doc = PresentationDocument.Open(file, true))
            {
                var slidePart = doc.PresentationPart.SlideParts.First();

                XDocument slideXDoc = slidePart.GetXDocument();

                XNamespace p = "http://schemas.openxmlformats.org/presentationml/2006/main";
                XNamespace a = "http://schemas.openxmlformats.org/drawingml/2006/main";

                XElement sh = slideXDoc.Root.Element(p + "cSld").Element(p + "spTree").Elements(p + "sp").First();
                XElement r = sh.Element(p + "txBody").Elements(a + "p").Elements(a + "r").Skip(0).FirstOrDefault();

                XElement caption = r.Element(a + "t");
                caption.SetAttributeValue("myAttribute", "123");

                slidePart.PutXDocument();
            }

            Console.ReadKey();
        }
    }

    public static class PtOpenXmlExtensions
    {
        public static XDocument GetXDocument(this OpenXmlPart part)
        {

            XDocument partXDocument = part.Annotation<XDocument>();
            if (partXDocument != null)
                return partXDocument;
            using (Stream partStream = part.GetStream())
            using (XmlReader partXmlReader = XmlReader.Create(partStream))
                partXDocument = XDocument.Load(partXmlReader);
            part.AddAnnotation(partXDocument);
            return partXDocument;
        }

        public static void PutXDocument(this OpenXmlPart part)
        {
            XDocument partXDocument = part.GetXDocument();
            if (partXDocument != null)
            {
                using (Stream partStream = part.GetStream(FileMode.Create, FileAccess.Write))
                using (XmlWriter partXmlWriter = XmlWriter.Create(partStream))
                    partXDocument.Save(partXmlWriter);
            }
        }
    }
}
```

**Comment by twsouthwick** [comment] 2017-11-17 04:10
@tomjebo @tarunchopra Can either of you answer this?

**Comment by ThomasBarnekow** [comment] 2017-11-17 18:55
This is a question on Open XML markup and its treatment by tools such as PowerPoint, rather than an issue with the Open XML SDK. Thus, stackoverflow.com would be the place to ask such questions.

To provide a high-level answer, Word will always happily throw away your custom markup. And you basically confirmed PowerPoint does the same. Therefore, custom XML parts would be the only way to store custom data.

**Comment by twsouthwick** [comment] 2017-11-19 23:48
Thanks @ThomasBarnekow for the insight! @prostovasya Hopefully this helps you get on track. Since this is not an issue with the SDK, I'm going to close this. Please open any further issues you find and please explore StackOverflow for questions on use.

**Closed by twsouthwick** 2017-11-19 23:48 UTC
Labels: question
