### ISSUE TITLE
For French Machines, decimal is changing to comma in Open XML

### ISSUE THREAD

**Issue by rah123mis** [OfficeDev/Open-XML-SDK#288] opened 2017-11-07 12:40 UTC
If we change the machine configuration in English(US) (but the machine still in france) also the problem remains the same.
While writing the decimal data in the cell of open xml it convert the '.' dot to ',' comma automatically.
![image](https://user-images.githubusercontent.com/33454031/32494245-e1ca9bba-c3e6-11e7-95c8-7e2d140529e5.jpg)

Cell Binding process
![cell binding one](https://user-images.githubusercontent.com/33454031/32494430-a79781f0-c3e7-11e7-8c85-6c8649dae6d5.JPG)
![cell formatting 1](https://user-images.githubusercontent.com/33454031/32494432-a830f5d8-c3e7-11e7-8bdf-517c20f1b175.JPG)

Thanks in Advance

**Comment by twsouthwick** [comment] 2017-11-12 01:06
@rah123mis can you provide a repro? The images are hard to see (and can't zoom in well). The following would be very helpful:

**Information**

- .NET Target: (ie .NET Framework, .NET Core, UWP, Xamarin, etc)
- DocumentFormat.OpenXml Version: (ie 2.7.2)

**Repro**

```csharp
// Please add a self-contained, minimum viable repro of the issue.
// If you require external resources, please provide a gist or GitHub repro
// An Xunit style test is preferred, but a console application would work too.
``` 

**Observed**

Please add your observed behavior here

**Expected**

Please add your expected behavior here.

**Comment by ThomasBarnekow** [comment] 2017-11-17 18:09
@rah123mis I'd say the Open XML SDK has (almost) nothing to do with your issue. It is your use of 
`number.ToString()` instead of `number.ToString(CultureInfo.InvariantCulture)` that leads to the problem.

As a matter of fact, if you need to represent a decimal number as a string, e.g., in HTML, CSS, or Open XML for that matter, you need to provide it in a culture-invariant format. For example, `123,4` will have to be represented as `123.4`. The problem is that `ToString()` will produce a culture-specific string, e.g., `123,4`. Therefore, whenever you need to make sure the string will be formatted in a specific way, you must use `ToString(CultureInfo.InvariantCulture)`.

**Comment by twsouthwick** [comment] 2017-11-17 18:30
Yeah, that sounds like a very plausible cause. @rah123mis I'm going to close this issue, but if you believe it is due to the SDK, please reopen with a repro.

**Closed by twsouthwick** 2017-11-17 18:30 UTC
Labels: bug, needs-repro
