### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by docati** [OfficeDev/Open-XML-SDK#8] opened 2014-07-24 19:15 UTC
First of all: for me the most important things is that Office itself can open the files; even if files are 100% valid to the specs, if Word cannot open them, my users complain. If it's not valid, but Word is fine with it, so are my users (and so am I :)).

Therefore, in my case the validation logic should only judge things as an error if Word cannot handle it as well. Otherwise it should treat the issue as a warning.

My issues:
1. Validation complains a lot about attributes on tables. Word does not.
2. Validation does NOT complain about a table cell without contents. Word does!
3. Validation does NOT complain about a faulty footer (which contains a textbox), Word does!
4. The constructor of the validator requires me to specify against which fileformat (2007/2010/2013) to validate. How can I determine the file format of an existing document? If that's possible, why doesn't the default constructor of the validator do so, instead of defaulting to 2007?

For nr 3 I have two sample files. The first is the 'broken' one where validation does not complain. The second one is the same file, but now corrected by Word 2013.
https://dl.dropboxusercontent.com/u/2496004/OoxmlSdk/BrokenFooter.docx
https://dl.dropboxusercontent.com/u/2496004/OoxmlSdk/BrokenFooter%20-%20Fixed%20By%20Word.docx

Personally I cannot see what exactly Word fixed for the footer. The XML is just slightly different. Although I use the OOXML SDK for file manipulation, I process the XML contents using xslt and then write back the resulting XML. Can this be the cause? (I doubt it, since process all document parts this way)

Regards,
Robert te Kaat | www.docati.com

**Comment by EricWhiteDev** [comment] 2015-07-24 05:27
Assigning this to v4.0 milestone, and to myself.

**Comment by Josh-Curry** [comment] 2017-01-11 19:20
Hi Robert, I spent some time looking into your questions and I'll address each of them in turn…

	1. Validation complains a lot about attributes on tables. Word does not.
		a. We recognize and acknowledge that the validation functionality has some issues that need to be addressed. We will be working to improve the reliability and accuracy of the validation in the future.

	2. Validation does NOT complain about a table cell without contents. Word does!
		a. In addition to what I mentioned previously, this is one instance where the SDK should be generating a validation error. Per MS-OI29500 section 2.1.167 it states that "If a tc element does not contain at least one p element, and that element is not the last child block-level element of the tc element, then Word will fail to open the file."

	3. Validation does NOT complain about a faulty footer (which contains a textbox), Word does!
		a. I was not able to reproduce this problem. Adding a textbox to the footer doesn't cause any issues by default. Do you still have the sample file or this? I was not able to retrieve the files that you posted previously via the links above.

	4. The constructor of the validator requires me to specify against which fileformat (2007/2010/2013) to validate. How can I determine the file format of an existing document? If that's possible, why doesn't the default constructor of the validator do so, instead of defaulting to 2007?
		a. I've posted a code snippet below that will show you how to determine the version of the file. In addition, we created a new issue #143 to track the feature request to have the SDK select the correct version automatically in the default constructor.

OpenXmlPackage package = WordprocessingDocument.Open(fileName, false);

foreach (IdPartPair part in package.Parts)
   {
      if (part.OpenXmlPart.GetType().ToString() == "DocumentFormat.OpenXml.Packaging.ExtendedFilePropertiesPart")
      {
         ExtendedFilePropertiesPart fileProps = (ExtendedFilePropertiesPart)part.OpenXmlPart;
         Debug.Print("Version: " + fileProps.Properties.Application.Text + " " + fileProps.Properties.ApplicationVersion.Text);
      }
}

**Closed by Josh-Curry** 2017-01-11 19:20 UTC
