### ISSUE TITLE
WordprocessingML PageMargin attributes' type not compliant

### ISSUE THREAD

**Issue by Nautigsam** [OfficeDev/Open-XML-SDK#42] opened 2015-06-09 15:14 UTC
I noticed that we use Int32 and UInt32 to store page margin values (left, top, right, bottom). However, the spec (§22.9.2.14 ST_TwipsMeasure) specifies that the type of the value depends on the value itself. It can be an integer or a decimal value with a unit specifier.
The result is there are some documents that can't be properly red, like those generated by Google Docs, because it uses decimal values for page margins.

**Comment by ThomasBarnekow** [comment] 2015-07-05 20:57
My understanding is that "1 twips", i.e., one twentieth of a point, is the finest resolution you get. Open XML documents can only store whole twipses, i.e., multiples of 1/1440. Therefore, you would have to round any number -- integer or decimal -- of inches, centimeters, or other units to the nearest twips value.  

This is also what happens in Microsoft Word, for example, when you define an indentation, for example. Regardless of the unit you choose to define the indentation, you will only find full twips values in the Open XML document.

**Comment by ThomasBarnekow** [comment] 2015-07-23 22:12
@Nautigsam Do you agree? Can we close this issue?

**Comment by EricWhiteDev** [comment] 2015-07-24 05:17
@ThomasBarnekow I think that this is actually an issue that possibly should be fixed.  The spec does say that the value can be something like 12.7mm, and I am guessing that the SDK does not allow for this.  I think this is a bug in the SDK.  Assigning to myself.

**Comment by ThomasBarnekow** [comment] 2015-07-24 08:34
@EricWhiteDev and @Nautigsam I've just seen that the specification of ST_TwipsMeasure changed between the 1st and 2nd edition of the standard. The 2nd edition added the option to use decimal numbers. The question, however, is which aspect has really changed. 

While §22.9.2.14 (ST_TwipsMeasure (Measurement in Twentieths of a Point)) says that the contents can be "a positive decimal number immediately following by a unit identifier", it also only provides an example for 720 Twips being represented as a decimal number, i.e., "12.7mm". What I'm reading, therefore, is that the contents still represent a "Twips Measure", meaning that decimal numbers would be rounded to the nearest whole Twips value (which is clearly what happens in Word).

For example, "10.0mm" (or "1cm" or "0.01m") would actually be approx. 566.9 Twips (rounded). If you represented that as a Twips value in Open XML, you'd see "567", i.e., "1.000125cm". The difference between 1cm and 1.000125cm is negligible, though.

If ST_TwipsMeasure only represents whole Twips values, these can be represented as integers, regardless of whether they are specified as "720" or "12.7mm", for example.

You should also have a look at §17.6.11 (pgMar (Page Margins)), which clearly says that the page margin values (e.g., left, top, right, bottom) are twentieths of a point. For example, the definition for the "left" attribute is as follows:

> Specifies the distance (in twentieths of a point) between the left edge of the page and the left edge of the text extents for this document.
>
> [Example: Consider a document where the left text extent must start two inches inside the page extent. To specify this boundary, the following page margins must specified in the WordprocessingML:
>
> <w:pgMar ... w:left="2880"/>
>
> This fragment specifies that the left margin must span 2880 twentieths of a point from the left edge of the page. end example]
>
> The possible values for this attribute are defined by the ST_TwipsMeasure simple type (§22.9.2.14).

**Comment by Nautigsam** [comment] 2015-07-24 09:03
That was exactly my point, and I think @EricWhiteDev got it. Thanks!

**Comment by ThomasBarnekow** [comment] 2015-07-24 09:38
@Nautigsam But mind you the issue is *not* the fact that "we use Int32 and UInt32 to store page margin values" (unless my interpretation of the standard is wrong). The issue is that the SDK might not allow an XML element like `<pgMar ... left="12.7mm" ... />`. If it allowed that attribute value, though, `myPageMargin.Left` would correctly return an unsigned integer Twips value of 720.

**Comment by Nautigsam** [comment] 2015-07-24 09:44
You are right, the problem is more in the parsing process which uses UInt32.Parse() or Int32.Parse() and ignores any possible use of unit specifier.

**Comment by EricWhiteDev** [comment] 2015-07-24 11:16
I have a few questions:
- Other than google docs, is this measurement ever written with a UOM?  I can query my document library for this.  I have been meaning to make a massive grep function for OxRunner that will quickly give a list of every Open XML document in the library that matches an RegEx, after each file has been converted to indented Flat OPC.
- How do we make a non-breaking change?  One option (as @ThomasBarnekow suggests) is to transform the value with the UOM into twips, leaving the type as is.  This is probably the easiest approach.
- Another option is to introduce another property that is a string, that returns the value with the UOM.  I am uncertain if this exists elsewhere in the SDK - have two properties that retrieve essentially the same value - in one case an Int32 that is always in twips, and in the other case the unparsed value in twips or some other UOM.
- Maybe we do both options simultaneously.

**Comment by ThomasBarnekow** [comment] 2015-07-24 12:28
@EricWhiteDev I've just played with those attributes. When you manually set the `left` attribute's value of the last section's `w:pgMar` element to `25.4mm`, for example (from whatever different value it might have had before), that new value will be picked up correctly by Word. However, should you save the document with Word, you'd then see `left="1440"` again. Word does not preserve the decimal value with the unit of measure. And it doesn't have to preserve that value, because the standard says that "conforming applications are not required to preserve units of measure between loading and saving a particular document" (see §22.9.2.12).

While Word is fine with "25.4mm", for example, `OpenXmlValidator` complains about this not being an integer value. While that's obviously right, this does not correctly reflect the standard and would have to be fixed. While I've not tested this, you would likely run into runtime errors trying to access these values.

I strongly believe that "transforming the value with the UOM into Twips" is exactly what Word does (and what the standard says in my interpretation). Therefore, we must preserve the API, using the property types unchanged. However, you can certainly provide the original string in an additional property if that's a requirement.

The most important fix would be to have the Open XML SDK accept these values and translate them correctly.

**Comment by Nautigsam** [comment] 2015-07-24 14:00
I agree, it's better to let the user choose how he handles values, keep UInt32 for TwipsMeasure and Int32 for SignedTwipsMeasure but provide a string property for raw value. It would be also necessary to implement these modifications for HpsMeasure, and maybe other ones. Anyway, Annex M give details about differences between ISO's version of standard and ECMA's version.

**Comment by goodhisotry** [comment] 2016-02-27 19:20
I downloaded Preview of the Open-Xml-Sdk v3.0.
But this issue isn't left unsolved.
Could you let me know what's going on?

**Comment by EricWhiteDev** [comment] 2016-02-27 20:32
Just checking, did you check out Office2016 branch? Please upload a file that does not validate properly.  Cheers

**Comment by goodhisotry** [comment] 2016-02-27 21:59
@EricWhiteDev.
Thank you for your repray.
I will attach the file.
[schemas_openxmlformats_org_wordprocessingml_2006_main.zip](https://github.com/OfficeDev/Open-XML-SDK/files/149587/schemas_openxmlformats_org_wordprocessingml_2006_main.zip)

**Closed** 2020-05-22 00:06 UTC
Labels: Office2016, bug, has-repro, no-issue-activity, schema
