### ISSUE TITLE
ToFlatOpcString fails with generated document

### ISSUE THREAD

**Issue by daniel-white** [OfficeDev/Open-XML-SDK#380] opened 2018-01-16 18:34 UTC
**Description**

`ToFlatOpcString` throws "Root element is missing." I'm trying to put this format into a VSTO add-in. When I enumerate `wordprocessingDocument.Package.GetParts()`, I get the relationship part back as an empty string (`ContentType = "application/vnd.openxmlformats-package.relationships+xml"`). Shouldn't `AddMainDocumentPart` take care of this under the covers?

**Information**

- .NET Target: .NET Core 2.0, .NET Framework 4.7
- DocumentFormat.OpenXml Version: 2.8.1

**Repro**

```csharp
using System;
using System.IO;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            using (MemoryStream stream = new MemoryStream())
            using (WordprocessingDocument wordprocessingDocument = WordprocessingDocument.Create(stream, WordprocessingDocumentType.Document))
            {
                MainDocumentPart mainDocumentPart = wordprocessingDocument.AddMainDocumentPart();
                Body body = new Body(new Paragraph(new Run(new RunProperties(new Bold()),
                    new Text("Hello world this should be bold"))));
                mainDocumentPart.Document = new Document(body);

                wordprocessingDocument.Save();

                Console.WriteLine(wordprocessingDocument.ToFlatOpcDocument());
            }

        }
    }
}
``` 

**Observed**

Exception:

```
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.GetContentsAsXml(PackagePart part)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.ToFlatOpcDocument(XProcessingInstruction instruction)
   at ConsoleApp1.Program.Main(String[] args)
```

**Expected**

That `ToFlatOpcString` doesn't throw and I get the resulting XML string.

**Comment by daniel-white** [comment] 2018-01-16 19:05
I can workaround it with

```

                foreach (PackagePart packagePart in wordprocessingDocument.Package.GetParts())
                {
                    if (packagePart.ContentType == "application/vnd.openxmlformats-package.relationships+xml")
                    {
                        using (Stream packagePartStream = packagePart.GetStream())
                        using (StreamWriter streamWriter = new StreamWriter(packagePartStream))
                        {
                            streamWriter.Write("<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"word/document.xml\"/></Relationships>");
                        }

                    }
                }
```

but that is a dirty hack.

**Comment by daniel-white** [comment] 2018-01-17 16:11
In my further digging there seems to be 1 or 2 problems.

1. `Save` doesn't actually invoke a save of this part. I tried modifying to call `Flush` on `_metroPackage`, but i got another exception.
2. `InitPart` does add the relationship to the `_metroPackage`, but it doesnt seem to flush out its content.

**Comment by daniel-white** [comment] 2018-01-17 16:18
So `System.IO.Packaging.Package` will call a private `FlushRelationships` on a `Flush` call, but the `OpenXmlPackage` does not call `Flush` on `Save`.

**Comment by tomjebo** [comment] 2018-01-17 19:01
@daniel-white thanks for reporting this and providing the extra information. I'll take a look. We did just update some of the Save functionality but not sure if that's related. @twsouthwick may know of top of head. otherwise, I'll check into it.

**Comment by daniel-white** [comment] 2018-01-17 19:05
Calling `Flush` on the package fails with other exceptions at different times.

**Comment by twsouthwick** [comment] 2018-01-17 19:05
This seems similar to an open issue. I added a fix for last release to enable saving when auto-save is disabled, but this was on close. Being able to save while the stream is still open is unfortunately blocked in CoreFx. Please see https://github.com/OfficeDev/Open-XML-SDK/issues/294 which is the tracking issue in this repository.

If you were to switch to v2.7.2, does it work? I want to make sure it is not a regression.

**Comment by twsouthwick** [comment] 2018-01-17 19:05
Wrong button...

**Comment by daniel-white** [comment] 2018-01-17 19:41
@twsouthwick not a regression with .net 4.7 or .net core 2.0 using v2.7.2. same exception.

**Comment by daniel-white** [comment] 2018-01-17 19:42
would another "stupid workaround" be to close the `WordprocessingDocument`, rewind the memory stream and reopen?

**Comment by twsouthwick** [comment] 2018-01-17 19:46
Yup. That's probably the best way to do it right now, although the stream itself will have to be recreated as it will be in  a disposed state.

**Comment by daniel-white** [comment] 2018-01-17 19:47
It worked, so when I pass a stream off to `Open`, it will cause it to be disposed?

**Comment by twsouthwick** [comment] 2018-01-17 19:50
It'll be disposed after closing it (which forces the save/flush). Can you post what you get working for posterity? Hopefully we'll get the fixes needed in CoreFx so we can make this easier, but for now, having possible work arounds will be helpful

**Comment by daniel-white** [comment] 2018-01-17 19:52
here's what i got working. im guessing a `MemoryStream` can be rewound since its just a wrapper for a `byte[]`.

```
 using (MemoryStream stream = new MemoryStream())
            {
                using (WordprocessingDocument wordprocessingDocument =
                    WordprocessingDocument.Create(stream, WordprocessingDocumentType.Document))
                {
                    MainDocumentPart mainDocumentPart = wordprocessingDocument.AddMainDocumentPart();

                    /*      foreach (PackagePart packagePart in wordprocessingDocument.Package.GetParts())
                          {
                              if (packagePart.ContentType == "application/vnd.openxmlformats-package.relationships+xml")
                              {
                                  using (Stream packagePartStream = packagePart.GetStream())
                                  using (StreamWriter streamWriter = new StreamWriter(packagePartStream))
                                  {
                                      streamWriter.Write("<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"word/document.xml\"/></Relationships>");
                                  }
          
                              }
                          } */


                    Body body = new Body(new Paragraph(new Run(new RunProperties(new Bold()),
                        new Text("Hello world this should be bold"))));
                    mainDocumentPart.Document = new Document(body);

                    wordprocessingDocument.Save();
                }

                stream.Seek(0, SeekOrigin.Begin);
                using (WordprocessingDocument doc = WordprocessingDocument.Open(stream, false))
                {
                    Console.WriteLine(doc.ToFlatOpcString());
                }
            }
```

**Comment by twsouthwick** [comment] 2018-01-17 19:58
It'll still through "ObjectDisposed" during some operations. If this does work, then maybe it doesn't get disposed during the package closing (can't remember off the top of my head)

**Comment by daniel-white** [comment] 2018-01-17 20:08
Fair enough.

On another note, the unit tests don't test this path at all, perhaps for this very reason.

What's troubling is that this is failing in .NET framework in the same way the .NET Core build does. adding a call to `doc.Package.Flush` fixes it on .NET framework. Are you guys going for parity here? Would a `#if NETFRAMEWORK` conditional inside of `Save` make sense to at least get the .net framework working?

**Comment by twsouthwick** [comment] 2018-01-17 20:13
We're going for behavior parity between .NET Core and .NET Framework. We could add a fix for .NET Framework only, though, and have a list of known issues for .NET Core....

**Comment by twsouthwick** [comment] 2018-01-17 20:14
As far as the tests are concerned, there are a lot of cases the tests don't cover unfortunately. It seems that as it was originally developed some integration tests were added for document conversion, but basic functionality don't have many unit tests. Feel free to add some, and mark as skipped with a link to the issues... building up tests is always a good thing!

**Comment by tomjebo** [comment] 2018-01-17 21:57
@daniel-white we do have FlatOpcTests.cs with ToFlatOpcString(). Can you add your test there instead?

**Comment by twsouthwick** [comment] 2018-01-24 22:51
I'm going to close this one as the issue is tracking in #294. Once that is fixed, we'll want to enable these tests.

**Closed by twsouthwick** 2018-01-24 22:51 UTC
Labels: bug, duplicate, has-repro

**Comment by twsouthwick** [comment] 2018-04-06 18:55
@daniel-white I've opened a PR to enable saving with a flag on `OpenXmlPackage.CanSave` to indicate whether the platform supports fully saving. It will still not work on .NET Core, but will allow saving when possible. Please have a look at #468 and give any feedback you may have.
