### ISSUE TITLE
Can't open file: Absolute URIs are not supported

### ISSUE THREAD

**Issue by santochan** [OfficeDev/Open-XML-SDK#69] opened 2015-12-21 05:29 UTC
I'm running OpenXMLSDK(2.5.0) on Mac OS 10.11.2 (EI Capitan) with Mono 4.2.1 .
When I'm trying to open a Docx file, I got this exception:
 `targetUri Parameter name: Absolute URIs are not supported`

My code is below:

``` c#
public static void Main (string[] args)
{
    Console.WriteLine ("Hello World!");
    using (WordprocessingDocument doc = WordprocessingDocument.Open ("/tmp/test_open.docx", true)) 
    {
          MainDocumentPart mainPart = doc.MainDocumentPart;
    }
}
```

Error stack:

``` shell
Unhandled Exception:
System.ArgumentException: targetUri
Parameter name: Absolute URIs are not supported
  at System.IO.Packaging.PackUriHelper.ResolvePartUri (System.Uri sourcePartUri, System.Uri targetUri) <0x32b0440 + 0x00187> in <filename unknown>:0
  at DocumentFormat.OpenXml.Packaging.OpenXmlPartContainer.LoadReferencedPartsAndRelationships (DocumentFormat.OpenXml.Packaging.OpenXmlPackage openXmlPackage, DocumentFormat.OpenXml.Packaging.OpenXmlPart sourcePart, DocumentFormat.OpenXml.Packaging.RelationshipCollection relationshipCollection, System.Collections.Generic.Dictionary`2 loadedParts) <0x32b3208 + 0x0021b> in <filename unknown>:0
  at DocumentFormat.OpenXml.Packaging.OpenXmlPart.Load (DocumentFormat.OpenXml.Packaging.OpenXmlPackage openXmlPackage, DocumentFormat.OpenXml.Packaging.OpenXmlPart parent, System.Uri uriTarget, System.String id, System.Collections.Generic.Dictionary`2 loadedParts) <0x32b4678 + 0x001eb> in <filename unknown>:0
  at DocumentFormat.OpenXml.Packaging.OpenXmlPartContainer.LoadReferencedPartsAndRelationships (DocumentFormat.OpenXml.Packaging.OpenXmlPackage openXmlPackage, DocumentFormat.OpenXml.Packaging.OpenXmlPart sourcePart, DocumentFormat.OpenXml.Packaging.RelationshipCollection relationshipCollection, System.Collections.Generic.Dictionary`2 loadedParts) <0x32b3208 + 0x00447> in <filename unknown>:0
  at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Load () <0x784b88 + 0x003eb> in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentException: targetUri
Parameter name: Absolute URIs are not supported
  at System.IO.Packaging.PackUriHelper.ResolvePartUri (System.Uri sourcePartUri, System.Uri targetUri) <0x32b0440 + 0x00187> in <filename unknown>:0
  at DocumentFormat.OpenXml.Packaging.OpenXmlPartContainer.LoadReferencedPartsAndRelationships (DocumentFormat.OpenXml.Packaging.OpenXmlPackage openXmlPackage, DocumentFormat.OpenXml.Packaging.OpenXmlPart sourcePart, DocumentFormat.OpenXml.Packaging.RelationshipCollection relationshipCollection, System.Collections.Generic.Dictionary`2 loadedParts) <0x32b3208 + 0x0021b> in <filename unknown>:0
  at DocumentFormat.OpenXml.Packaging.OpenXmlPart.Load (DocumentFormat.OpenXml.Packaging.OpenXmlPackage openXmlPackage, DocumentFormat.OpenXml.Packaging.OpenXmlPart parent, System.Uri uriTarget, System.String id, System.Collections.Generic.Dictionary`2 loadedParts) <0x32b4678 + 0x001eb> in <filename unknown>:0
  at DocumentFormat.OpenXml.Packaging.OpenXmlPartContainer.LoadReferencedPartsAndRelationships (DocumentFormat.OpenXml.Packaging.OpenXmlPackage openXmlPackage, DocumentFormat.OpenXml.Packaging.OpenXmlPart sourcePart, DocumentFormat.OpenXml.Packaging.RelationshipCollection relationshipCollection, System.Collections.Generic.Dictionary`2 loadedParts) <0x32b3208 + 0x00447> in <filename unknown>:0
  at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Load () <0x784b88 + 0x003eb> in <filename unknown>:0
```

Does anyone know what is the problem here? Thank you.

**Comment by KennedyTedesco** [comment] 2016-01-13 18:54
+1 The same issue here using Mono.

**Comment by EricWhiteDev** [comment] 2016-01-14 04:55
The SDK hasn't been systematically checked out with Mono, although I have heard anecdotal reports of success using it.  I have successfully made a 'hello world' Open XML SDK app using Mono, but that's about it.

There have been reported issues associated with the implementation of System.IO.Packaging that comes with Mono - minor variations in semantics in certain limited scenarios that cause errors.  I have not researched if it would be possible to code around those issues, but have heard from other developers that they have got it working.  It would be necessary to do a systematic test of the SDK on Mono to understand all issues.  The PackUriHelper class is not very complicated, so there certainly should be a reasonable way to solve the above issue, but without precise details, it is difficult to know what the issue is.

It could, in theory, be possible to use the new, open source System.IO.Packaging that comes with the SDK, which in turn uses System.IO.Compression.  However, I have heard other anecdotal evidence that there are issues/bugs with Mono's implementation of System.IO.Compression.  Again, would be necessary to do a systematic test to determine if this is a good way forward.

If the Mono implementation of System.IO.Compression isn't workable, it could be possible to port the COREFX implementation of System.IO.Compression to Mono.  COREFX is licensed using the MIT license, so no legal issues here.  I don't have any idea of what issues one might encounter when doing this port.

Long story short, there probably is a way forward to get the SDK to work reliably and predictably with Mono, but it will require some work and research.  This currently is not on the schedule.  If this is vital to your project, please let us know.  This feedback is super important to those who are in charge, so that they know where to allocate resources for the SDK.

Instead of using Mono, would it be an option to use COREFX?  (https://github.com/dotnet/corefx)  It works on Linux and Mac (and of course Windows).  The folks in charge are discussing the desirability of porting the SDK to COREFX.  If you have an opinion about this, please let us know.

We are currently in the process of expanding the XUnit tests for the SDK.  (Commit to the repo should happen today!)  These XUnit tests are vital to doing the port of the SDK to Mono / COREFX.  After doing the port, if the new set of XUnit tests run, we can have good confidence about the functionality of the SDK on that port.  Without these tests, we would have no good way of determining whether the SDK is working properly or not on Mono / COREFX.

So, we are doing the right stuff to enable porting to other platforms, but the actual porting work hasn't really started.  The System.IO.Packaging in COREFX is identical to the System.IO.Packaging that is included in the Open XML SDK, so we are a good step along in doing this port, but more work remains.

Leaving this issue open to keep visibility.

**Comment by santochan** [comment] 2016-03-03 02:25
Thank a lot for introducing COREFX. I'll try it out!

**Comment by codepandy** [comment] 2016-07-22 10:07
@santochan Do you solve it?

**Comment by tarunchopra** [comment] 2017-01-23 19:04
@codepandy : 

Please test your scenario with the latest bits as we have replaced custom System.IO.Packaging (https://github.com/OfficeDev/Open-XML-SDK/commit/5ef669ba14b043ece9e1fa4643c294d9120d4a4e ). If it still does not work with latest bits, let us know.

**Comment by jvanriel** [comment] 2017-03-29 22:05
I'm running with the latest mono 4.8 on Debian 8.7 and the latest NuGet package for Open-XML-SDK.

I'm still getting this exception, even when I temporarily change the current working directory of the process such that i use relative files instead of absolute paths. I've tried with System.IO.Packaging but to no avail. 

Creating a new file works without issues. Has anyone code that successfully opens an existing Excel file for edit? 

This is a very important project for us I'm desperate to find a solution or workaround.

**Comment by igitur** [comment] 2017-03-29 22:20
@jvanriel When I last looked at this issue, there was also a bug In Mono itself. I attempted a poor pull request at https://github.com/mono/mono/pull/3630 but with those changes I was able to manipulate xlsx files.

**Comment by jvanriel** [comment] 2017-03-30 11:06
It looks like the mono pull request form igitur is not (yet) merged.  From an Open-XML-SDK perspective a simple test like the one below : create an .xlsx file (which works) and then open that file again (which fails) seems like a pretty fundamental issue. 

As far as i understand both Open-XML-SDK and Mono are under the same MS umbrella. Could I get some guidance from an insider about when this issue could be fixed and released and as of when we could consider to use a Linux-Mono/OpenXML for production use? 

I've used the joelharkes.DocumentFormat.OpenXml version 2.7.1 package for this. Here is the test:

using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Spreadsheet;

namespace ExcelOpen
{
	class MainClass
	{
		public static void Main(string[] args)
		{
			string fileName = "/tmp/test.xlsx";

			SpreadsheetDocument document = SpreadsheetDocument.Create(fileName, SpreadsheetDocumentType.Workbook);
			WorkbookPart workbookPart = document.AddWorkbookPart();
			workbookPart.Workbook = new Workbook();
			WorksheetPart worksheetPart = workbookPart.AddNewPart<WorksheetPart>();
			worksheetPart.Worksheet = new Worksheet();
			workbookPart.Workbook.Save();

			SpreadsheetDocument.Open(fileName, true);
		}
	}
}

Note that when using only a workbook (without a sheet) there is no issue.

**Comment by twsouthwick** [comment] 2017-11-17 02:33
This appears to be fixed on Mono. A similar issue is seen on Xamarin, but is due to: https://github.com/OfficeDev/Open-XML-SDK/issues/249. Closing this issue.

**Closed by twsouthwick** 2017-11-17 02:33 UTC
