### ISSUE TITLE
Validator fails to notice changes to first file when comparing files

### ISSUE THREAD

**Issue by Themanwithoutaplan** [OfficeDev/Open-XML-SDK#52] opened 2015-07-28 12:08 UTC
I often use the validator to compare generated files versus ones created by Excel and tweak code as a result. If I then use the validator to compare the same files in the same order it does not seem to notice if the first file has changed.

A refresh option would be best, of course.

**Comment by EricWhiteDev** [comment] 2015-07-28 12:32
Thanks, good to know. I will assign it to myself, and for milestone 4.0 (which is after the release for Office 2016).

**Comment by twsouthwick** [comment] 2017-11-17 15:12
@Themanwithoutaplan Can you give an example of what you mean? I do see that the validators track state, but I want to make sure we're dealing with the issue you've seen.

**Comment by Themanwithoutaplan** [comment] 2017-11-17 15:50
I often compare file A with file B. When I do a comparison and select file A first, it remains as the file to be compared with until I select a different source. The target has to be selected each time. If I make changes to B, these are reflected because I have to select the target each time. However, if A has changed in the meantime, these changes will not show up in the comparison. It seems that the validator is caching the file.

Does this make sense?

**Comment by twsouthwick** [comment] 2017-11-17 15:52
By repro, I'm referring to the actual code you are using to compare (there are a few ways of setting it up). Also, does it matter which documents? How do you tell the changes don't show up? A set of clear steps (preferably with code) that will detail how to reproduce the issue and what you are seeing vs what you are expecting to see. I can guess at some of these steps from your description, but the more exact you are, the more likely we'll address the right issue :)

**Comment by Themanwithoutaplan** [comment] 2017-11-17 15:54
No code, using the GUI tool.  I'll see if I can create a noddy example to make it clear via screenshot.

**Comment by twsouthwick** [comment] 2017-11-17 15:55
What do you mean the GUI tool? There is no GUI in this project.

**Comment by Themanwithoutaplan** [comment] 2017-11-17 15:58
I'm referring to the OOXML SDK Productivity Tool which I thought was part of the project.

**Comment by twsouthwick** [comment] 2017-11-17 16:00
It builds on top of it I believe, but this project is the underlying library that does the actual OpenXml validation. It may be that the GUI is doing some caching that may not show up in a pure code example; then the issue is with the GUI. Are you familiar at all with the library? If not, then screenshots and step by step directions will suffice.

**Comment by Themanwithoutaplan** [comment] 2017-11-17 16:04
I think the tool was originally part of the project but possibly split off or abandoned later. I don't think there's been an update since v2.5. I'm not familiar with the underlying library so screenshots will have to suffice. Thanks very much for picking this up.

**Comment by Themanwithoutaplan** [comment] 2017-11-17 16:19
<img width="1773" alt="bildschirmfoto 2017-11-17 um 17 16 41" src="https://user-images.githubusercontent.com/1080058/32957137-23e66fde-cbbb-11e7-9401-4239e507b580.png">

In this example I compared A with B. I then renamed the worksheet in A to "Table2". As you can see workbook.xml has not updated to reflect this.

Once I figured this out of course I always made sure to compare files in the right order but there are times when I'm making changes to both files.

**Comment by twsouthwick** [comment] 2017-11-17 16:22
Thanks - it's very possible this is a bug with the way that the GUI handles things. We should check, though, if an equivalent set up in code repros the same thing.

**Closed** 2018-01-25 19:48 UTC
Labels: bug, has-repro
