### ISSUE TITLE
Process formula in Word document using OpenXML

### ISSUE THREAD

**Issue by imn1x** [OfficeDev/Open-XML-SDK#234] opened 2017-08-18 09:30 UTC
We have a docx file with merge fields, and formulae with merge fields.
This was processing using interop DCOM object
When the same document is processed using Open XML SDK, only the merge fields are replaced, but formulae are not recognized.

Any solution to process formula using OpenXML.

Thanks
Imran

**Comment by twsouthwick** [comment] 2017-11-17 15:25
Hi @imn1x . This appears to be a duplicate of https://github.com/OfficeDev/Open-XML-SDK/issues/275. I'm going to close this, but please reopen with a concise repro if this is in fact a different issue.

**Closed by twsouthwick** 2017-11-17 15:25 UTC
